In [1]:
%load_ext autoreload
%autoreload 2
from innolux import *

In [2]:
# set polars show all rows
pl.Config.set_tbl_rows(-1)

polars.config.Config

In [3]:
cwd = data_path / "T2 6117" / "pds"

In [8]:
cwd

WindowsPath('D:/Documents/Projects/innolux/data/T2 6117')

In [4]:
def edc_get(
    edc_raw: pl.DataFrame, 
    step: tuple[str, str], 
    filter: list[pl.Expr] | None = None,
) -> pl.DataFrame:
    result = (
        edc_raw.filter(
            pl.col("SUB_EQUIP_ID").str.contains(step[0]),
            pl.col("PARAM_NAME").str.contains(step[1])
        )
        # .select(
        #     "GLASS_ID", "SUB_EQUIP_ID", "PARAM_NAME", "AVG_VALUE"
        # )
        .select(
            "ID", 
            pl.col("PARAM_VALUE").cast(float)
        )
    )
    
    if filter is not None:
        result = result.filter(*filter)
    
    return result.group_by(['ID']).mean()

In [5]:
# lf - lazy data frame
eda_lf = pl.scan_csv(cwd / "pds-*.csv", ignore_errors=True)
eda_raw = (
    eda_lf
        .with_columns(
            pl.col("PARAM_VALUE")
                .cast(float, strict=False)
                .fill_null(0),
            pl.col("GLASS_ID").alias("ID"),
        )
        .filter(pl.col("PARAM_VALUE") > 0)
        .collect()
)

In [16]:
condition = pl.read_excel(cwd / "condition.xlsx")

In [17]:
condition

shape: (26, 3)
┌────────────────────┬────────────────┬────────────────┐
│ Condition          ┆ TFT            ┆ CF             │
│ ---                ┆ ---            ┆ ---            │
│ str                ┆ str            ┆ str            │
╞════════════════════╪════════════════╪════════════════╡
│ LC-1098            ┆ 611A2APB2HP221 ┆ 611A2FPB2CBT15 │
│ LC-1098            ┆ 611A2APB2HP208 ┆ 611A2FPB2CBT23 │
│ STD-首件           ┆ 611A2APB2HP213 ┆ 611A2FPB2C9T27 │
│ STD                ┆ 611A2APB2HP212 ┆ 611A2FPB2CDT47 │
│ STD                ┆ 611A2APB2HP216 ┆ 611A2FPB2CET58 │
│ PAUV 260           ┆ 611A2APB2HP204 ┆ 611A2FPB2C8T35 │
│ PAUV 260           ┆ 611A2APB2HP214 ┆ 611A2FPB2CDT41 │
│ PAUV 220           ┆ 611A2APB2HP206 ┆ 611A2FPB2CGT19 │
│ PAUV 220           ┆ 611A2APB2HP211 ┆ 611A2FPB2CBT32 │
│ 24 + 24            ┆ 611A2APB2HP201 ┆ 611A2FPB2C8T50 │
│ 24 + 24            ┆ 611A2APB2HP202 ┆ 611A2FPB2CCT06 │
│ PAPB to ARO 24 hr  ┆ 611A2APB2HP209 ┆ 611A2FPB2CBT09 │
│ PAPB to ARO 24 hr  ┆ 611A2APB2HP210 ┆ 611A2FPB2CCT50 │
│ PIPB to PAPB 24 hr ┆ 611A2APB2HP205 ┆ 611A2FPB2C8T42 │
│ PIPB to PAPB 24 hr ┆ 611A2APB2HP203 ┆ 611A2FPB2CBT54 │
│ ODF to SEUV 150 s  ┆ 611A2APB2HP215 ┆ 611A2FPB2CBT16 │
│ ODF to SEUV 150 s  ┆ 611A2APB2HP220 ┆ 611A2FPB2C8T46 │
│ ODF 加抽 95 s      ┆ 611A2APB2HP218 ┆ 611A2FPB2CET14 │
│ ODF 加抽 65 s      ┆ 611A2APB2HP207 ┆ 611A2FPB2CDT35 │
│ ODF 加抽 65 s      ┆ 611A2APB2HP219 ┆ 611A2FPB2CAT09 │
│ ARO to ODF 60 min  ┆ 611A2APB2HP222 ┆ 611A2FPB2CBT22 │
│ ARO to ODF 60 min  ┆ 611A2APB2HP223 ┆ 611A2FPB2CET07 │
│ SEUV 5000          ┆ 611A2APB2HP225 ┆ 611A2FPB2CDT04 │
│ SEUV 5000          ┆ 611A2APB2HP226 ┆ 611A2FPB2CGT16 │
│ SEUV 7000          ┆ 611A2APB2HP227 ┆ 611A2FPB2CBT25 │
│ SEUV 7000          ┆ 611A2APB2HP228 ┆ 611A2FPB2CCT55 │
└────────────────────┴────────────────┴────────────────┘

In [111]:
eda_lf.filter(pl.col("SUB_EQUIP_ID").str.contains(r"2CPHA340")).head().collect()

shape: (5, 36)
┌────────────────┬────────────────┬─────────────────────┬─────────────────────┬───┬───────┬─────────────────┬─────┬──────┐
│ STEP_ID        ┆ GLASS_ID       ┆ PROCESS_START_TIME  ┆ PROCESS_END_TIME    ┆ … ┆ COUNT ┆ PARAM_STR_VALUE ┆ RN  ┆      │
│ ---            ┆ ---            ┆ ---                 ┆ ---                 ┆   ┆ ---   ┆ ---             ┆ --- ┆ ---  │
│ str            ┆ str            ┆ str                 ┆ str                 ┆   ┆ str   ┆ str             ┆ i64 ┆ str  │
╞════════════════╪════════════════╪═════════════════════╪═════════════════════╪═══╪═══════╪═════════════════╪═════╪══════╡
│ 6220_PH3_PA_UV ┆ 611A2APB2HP201 ┆ 2026/01/22 17:23:43 ┆ 2026/01/22 17:50:26 ┆ … ┆       ┆                 ┆ 1   ┆ null │
│ 6220_PH3_PA_UV ┆ 611A2APB2HP201 ┆ 2026/01/22 17:23:43 ┆ 2026/01/22 17:50:26 ┆ … ┆       ┆                 ┆ 2   ┆ null │
│ 6220_PH3_PA_UV ┆ 611A2APB2HP201 ┆ 2026/01/22 17:23:43 ┆ 2026/01/22 17:50:26 ┆ … ┆       ┆                 ┆ 3   ┆ null │
│ 6220_PH3_PA_UV ┆ 611A2APB2HP201 ┆ 2026/01/22 17:23:43 ┆ 2026/01/22 17:50:26 ┆ … ┆       ┆                 ┆ 4   ┆ null │
│ 6220_PH3_PA_UV ┆ 611A2APB2HP201 ┆ 2026/01/22 17:23:43 ┆ 2026/01/22 17:50:26 ┆ … ┆       ┆                 ┆ 5   ┆ null │
└────────────────┴────────────────┴─────────────────────┴─────────────────────┴───┴───────┴─────────────────┴─────┴──────┘

In [70]:
(
    eda_raw
        .filter(
            pl.col("ID") == "611A2APB2HP225",
            pl.col("SUB_EQUIP_ID").str.contains(r"2CASM\d+"),
            pl.col("PARAM_NAME").str.contains(r"ODFIN_UV_QTime"),
            # pl.col("PARAM_NAME").str.contains(r"Oven_\d_Temp\d"),
            # pl.col("PARAM_VALUE").is_between(500,700),
        )
        .select(
            "ID", 
            "SUB_EQUIP_ID",
            "PARAM_NAME",
            "PARAM_VALUE"
        )
        # .slice(110,20)
)

shape: (1, 4)
┌────────────────┬──────────────┬────────────────┬─────────────┐
│ ID             ┆ SUB_EQUIP_ID ┆ PARAM_NAME     ┆ PARAM_VALUE │
│ ---            ┆ ---          ┆ ---            ┆ ---         │
│ str            ┆ str          ┆ str            ┆ f64         │
╞════════════════╪══════════════╪════════════════╪═════════════╡
│ 611A2APB2HP225 ┆ 2CASM1C0     ┆ ODFIN_UV_QTime ┆ 307.0       │
└────────────────┴──────────────┴────────────────┴─────────────┘

In [42]:
t2_edc_steps = {
    "PIPR TEMP": {"step": (r"2CPIL\d+", r"PreCur\d+_temp"), "filter": None},
    "PIPR TIME": {"step": (r"2CPIL\d+", r"PreCur\d+_Time"), "filter": None},
    "PIPB TEMP": {"step": (r"2CPIL\d+", r"Oven_Temp_\d+"), "filter": None},
    "PIPB TIME": {"step": (r"2CPIL\d+", r"Heating_Time"), "filter": None},
    "PAUV": {"step": (r"2CPHA\d+", r"\d-\d exposure"), "filter": None},
    "PAPB TEMP": {"step": (r"2CPHA\d+", r"Baking temp zone\d+"), "filter": None},
    "PAPB TIME": {"step": (r"2CPHA\d+", r"Heating_Time"), "filter": None},
    "BOOX TEMP": {"step": (r"2CASM\d+", r"Oven_Temp_\d+"), "filter": None},
    "BOOX TIME": {"step": (r"2CASM\d30", r"Heating_Time"), "filter": None},
    "SEUV": {"step": (r"2CASM\dC0", r"UV_Energy"), "filter": None},
    "SEPB TEMP": {"step": (r"2CASM\dD0", r"Temp"), "filter": None},
    "SEPB TIME": {"step": (r"2CASM\dD0", r"Heating_Time"), "filter": None},
}
eda = eda_raw.select("ID").unique()
for step, kwargs in t2_edc_steps.items():
    eda = eda.join(
        edc_get(eda_raw, **kwargs)
        .select(
            "ID",
            pl.col("PARAM_VALUE").alias(step),
        ),
        on='ID',
        how='left',
    )
eda

shape: (52, 13)
┌────────────────┬───────────┬───────────┬────────────┬───┬───────────┬───────┬───────────┬───────────┐
│ ID             ┆ PIPR TEMP ┆ PIPR TIME ┆ PIPB TEMP  ┆ … ┆ BOOX TIME ┆ SEUV  ┆ SEPB TEMP ┆ SEPB TIME │
│ ---            ┆ ---       ┆ ---       ┆ ---        ┆   ┆ ---       ┆ ---   ┆ ---       ┆ ---       │
│ str            ┆ f64       ┆ f64       ┆ f64        ┆   ┆ f64       ┆ f64   ┆ f64       ┆ f64       │
╞════════════════╪═══════════╪═══════════╪════════════╪═══╪═══════════╪═══════╪═══════════╪═══════════╡
│ 611A2APB2HP215 ┆ 135.0     ┆ 80.0      ┆ 210.966667 ┆ … ┆ 608.0     ┆ 600.0 ┆ 120.0     ┆ 3649.0    │
│ 611A2APB2HP228 ┆ 135.0     ┆ 80.0      ┆ 210.733333 ┆ … ┆ 604.0     ┆ 700.0 ┆ 119.98    ┆ 3648.0    │
│ 611A2FPB2CCT55 ┆ 135.0     ┆ 80.0      ┆ 210.516667 ┆ … ┆ 604.0     ┆ null  ┆ null      ┆ null      │
│ 611A2FPB2C8T46 ┆ 135.0     ┆ 80.0      ┆ 210.666667 ┆ … ┆ 604.0     ┆ null  ┆ null      ┆ null      │
│ 611A2APB2HP206 ┆ 135.0     ┆ 80.0      ┆ 210.933333 ┆ … ┆ 604.0     ┆ 600.0 ┆ 119.98    ┆ 3649.0    │
│ 611A2FPB2CCT50 ┆ 135.0     ┆ 80.0      ┆ 210.483333 ┆ … ┆ 604.0     ┆ null  ┆ null      ┆ null      │
│ 611A2FPB2CGT16 ┆ 135.0     ┆ 80.0      ┆ 211.0      ┆ … ┆ 604.0     ┆ null  ┆ null      ┆ null      │
│ 611A2APB2HP219 ┆ 135.0     ┆ 80.0      ┆ 210.633333 ┆ … ┆ 604.0     ┆ 600.0 ┆ 119.98    ┆ 3648.0    │
│ 611A2FPB2CGT19 ┆ 135.0     ┆ 80.0      ┆ 210.766667 ┆ … ┆ 604.0     ┆ null  ┆ null      ┆ null      │
│ 611A2FPB2CBT25 ┆ 135.0     ┆ 80.0      ┆ 210.516667 ┆ … ┆ 604.0     ┆ null  ┆ null      ┆ null      │
│ 611A2APB2HP201 ┆ 135.0     ┆ 80.0      ┆ 210.866667 ┆ … ┆ 604.0     ┆ 600.0 ┆ 120.0     ┆ 3648.0    │
│ 611A2FPB2CBT22 ┆ 135.0     ┆ 80.0      ┆ 211.0      ┆ … ┆ 604.0     ┆ null  ┆ null      ┆ null      │
│ 611A2FPB2CDT04 ┆ 135.0     ┆ 80.0      ┆ 211.0      ┆ … ┆ 604.0     ┆ null  ┆ null      ┆ null      │
│ 611A2FPB2CAT09 ┆ 135.0     ┆ 80.0      ┆ 210.9      ┆ … ┆ 604.0     ┆ null  ┆ null      ┆ null      │
│ 611A2FPB2C9T27 ┆ 135.0     ┆ 80.0      ┆ 210.633333 ┆ … ┆ 604.0     ┆ null  ┆ null      ┆ null      │
│ 611A2APB2HP203 ┆ 135.0     ┆ 80.0      ┆ 210.9      ┆ … ┆ 604.0     ┆ 600.0 ┆ 120.0     ┆ 3649.0    │
│ 611A2APB2HP208 ┆ 135.0     ┆ 80.0      ┆ 210.35     ┆ … ┆ 604.0     ┆ 600.0 ┆ 120.02    ┆ 3649.0    │
│ 611A2FPB2CBT09 ┆ 135.0     ┆ 80.0      ┆ 210.8      ┆ … ┆ 604.0     ┆ null  ┆ null      ┆ null      │
│ 611A2FPB2CBT54 ┆ 135.0     ┆ 80.0      ┆ 210.633333 ┆ … ┆ 604.0     ┆ null  ┆ null      ┆ null      │
│ 611A2APB2HP205 ┆ 135.0     ┆ 80.0      ┆ 210.8      ┆ … ┆ 604.0     ┆ 600.0 ┆ 119.98    ┆ 3649.0    │
│ 611A2FPB2C8T42 ┆ 135.0     ┆ 80.0      ┆ 210.633333 ┆ … ┆ 604.0     ┆ null  ┆ null      ┆ null      │
│ 611A2APB2HP211 ┆ 135.0     ┆ 80.0      ┆ 211.033333 ┆ … ┆ 605.0     ┆ 600.0 ┆ 120.0     ┆ 3649.0    │
│ 611A2FPB2CDT47 ┆ 135.0     ┆ 80.0      ┆ 210.633333 ┆ … ┆ 604.0     ┆ null  ┆ null      ┆ null      │
│ 611A2FPB2C8T50 ┆ 135.0     ┆ 80.0      ┆ 210.733333 ┆ … ┆ 604.0     ┆ null  ┆ null      ┆ null      │
│ 611A2FPB2CBT16 ┆ 135.0     ┆ 80.0      ┆ 210.666667 ┆ … ┆ 608.0     ┆ null  ┆ null      ┆ null      │
│ 611A2APB2HP204 ┆ 135.0     ┆ 80.0      ┆ 210.866667 ┆ … ┆ 605.0     ┆ 600.0 ┆ 120.0     ┆ 3673.0    │
│ 611A2APB2HP210 ┆ 135.0     ┆ 80.0      ┆ 210.383333 ┆ … ┆ 604.0     ┆ 600.0 ┆ 120.0     ┆ 3648.0    │
│ 611A2FPB2CET07 ┆ 135.0     ┆ 80.0      ┆ 211.0      ┆ … ┆ 605.0     ┆ null  ┆ null      ┆ null      │
│ 611A2APB2HP213 ┆ 135.0     ┆ 80.0      ┆ 210.966667 ┆ … ┆ 604.0     ┆ 600.0 ┆ 120.0     ┆ 3648.0    │
│ 611A2FPB2CBT23 ┆ 135.0     ┆ 80.0      ┆ 210.833333 ┆ … ┆ 604.0     ┆ null  ┆ null      ┆ null      │
│ 611A2FPB2CBT32 ┆ 135.0     ┆ 80.0      ┆ 210.766667 ┆ … ┆ 605.0     ┆ null  ┆ null      ┆ null      │
│ 611A2APB2HP216 ┆ 135.0     ┆ 80.0      ┆ 210.8      ┆ … ┆ 604.0     ┆ 600.0 ┆ 120.0     ┆ 3648.0    │
│ 611A2APB2HP225 ┆ 135.0     ┆ 80.0      ┆ 210.766667 ┆ … ┆ 604.0     ┆ 500.0 ┆ 120.06    ┆ 3648.0    │
│ 611A2APB2HP223 ┆ 135.0     ┆ 80.0      ┆ 210.766667 ┆ … ┆ 605.0     ┆ 600.0 ┆ 120.0     ┆ 3649.0    │
│ 611A2APB2HP207 ┆ 135.0     ┆ 80.0      ┆ 210.316667 ┆ … ┆ 604.0     ┆ 600.0 ┆ 119.98    ┆ 3647.0    │
│ 611A2APB2HP221 ┆ 135.0     ┆ 80.0      ┆ 210.733333 ┆ … ┆ 605.0     ┆ 600.0 ┆ 119.98    ┆ 3648.0    │
│ 611A2FPB2CDT35 ┆ 135.0     ┆ 80.0      ┆ 210.9      ┆ … ┆ 604.0     ┆ null  ┆ null      ┆ null      │
│ 611A2FPB2CET14 ┆ 135.0     ┆ 80.0      ┆ 210.666667 ┆ … ┆ 604.0     ┆ null  ┆ null      ┆ null      │
│ 611A2FPB2CDT41 ┆ 135.0     ┆ 80.0      ┆ 211.0      ┆ … ┆ 605.0     ┆ null  ┆ null      ┆ null      │
│ 611A2APB2HP214 ┆ 135.0     ┆ 80.0      ┆ 210.866667 ┆ … ┆ 605.0     ┆ 600.0 ┆ 120.0     ┆ 3648.0    │
│ 611A2APB2HP226 ┆ 135.0     ┆ 80.0      ┆ 210.7      ┆ … ┆ 604.0     ┆ 500.0 ┆ 120.02    ┆ 3648.0    │
│ 611A2APB2HP227 ┆ 135.0     ┆ 80.0      ┆ 210.733333 ┆ … ┆ 604.0     ┆ 700.0 ┆ 119.98    ┆ 3649.0    │
│ 611A2APB2HP220 ┆ 135.0     ┆ 80.0      ┆ 210.8      ┆ … ┆ 604.0     ┆ 600.0 ┆ 120.04    ┆ 3649.0    │
│ 611A2APB2HP222 ┆ 135.0     ┆ 80.0      ┆ 210.766667 ┆ … ┆ 604.0     ┆ 600.0 ┆ 119.96    ┆ 3648.0    │
│ 611A2APB2HP218 ┆ 135.0     ┆ 80.0      ┆ 210.733333 ┆ … ┆ 604.0     ┆ 600.0 ┆ 120.04    ┆ 3647.0    │
│ 611A2FPB2C8T35 ┆ 135.0     ┆ 80.0      ┆ 210.666667 ┆ … ┆ 605.0     ┆ null  ┆ null      ┆ null      │
│ 611A2FPB2CCT06 ┆ 135.0     ┆ 80.0      ┆ 210.533333 ┆ … ┆ 604.0     ┆ null  ┆ null      ┆ null      │
│ 611A2FPB2CBT15 ┆ 135.0     ┆ 80.0      ┆ 210.833333 ┆ … ┆ 605.0     ┆ null  ┆ null      ┆ null      │
│ 611A2APB2HP209 ┆ 135.0     ┆ 80.0      ┆ 210.366667 ┆ … ┆ 604.0     ┆ 600.0 ┆ 120.0     ┆ 3649.0    │
│ 611A2APB2HP212 ┆ 135.0     ┆ 80.0      ┆ 211.033333 ┆ … ┆ 604.0     ┆ 600.0 ┆ 119.86    ┆ 3654.0    │
│ 611A2FPB2CET58 ┆ 135.0     ┆ 80.0      ┆ 210.666667 ┆ … ┆ 604.0     ┆ null  ┆ null      ┆ null      │
│ 611A2APB2HP202 ┆ 135.0     ┆ 80.0      ┆ 210.9      ┆ … ┆ 604.0     ┆ 600.0 ┆ 119.96    ┆ 3647.0    │
└────────────────┴───────────┴───────────┴────────────┴───┴───────────┴───────┴───────────┴───────────┘

In [43]:
(condition
    .join(
        eda.select([col for col in eda.columns if eda[col].null_count() == 0]),
        left_on="CF",
        right_on='ID',
        suffix="_CF",
        maintain_order="left",
    )
    .join(
        eda,
        left_on="TFT",
        right_on="ID",
        suffix=" - T",
        maintain_order="left",
    )
    .select(
        pl.col('Condition'),
        pl.col('TFT'),
        pl.col('CF'),
        pl.col('PIPR TEMP - T'),
        pl.col('PIPR TEMP').alias('PIPR TEMP - C'),
        pl.col('PIPR TIME - T'),
        pl.col('PIPR TIME').alias('PIPR TIME - C'),
        pl.col('PIPB TEMP - T'),
        pl.col('PIPB TEMP').alias('PIPB TEMP - C'),
        pl.col('PIPB TIME - T'),
        pl.col('PIPB TIME').alias('PIPB TIME - C'),
        pl.col('PAUV - T'),
        pl.col('PAUV').alias('PAUV - C'),
        pl.col('PAPB TEMP - T'),
        pl.col('PAPB TEMP').alias('PAPB TEMP - C'),
        pl.col('PAPB TIME - T'),
        pl.col('PAPB TIME').alias('PAPB TIME - C'),
        pl.col('BOOX TEMP'),
        pl.col('BOOX TIME'),
        # pl.col('ODFX Q2'),
        pl.col('SEUV') * 10, # change unit to mJ
        pl.col('SEPB TEMP'),
        pl.col('SEPB TIME'),
    )
    .write_excel(cwd / "eda_summary.xlsx")
)

In [8]:
qtime_raw = pl.read_excel(cwd / '6117 history-td.xlsx')

In [13]:
(
    qtime_raw
        .filter(
            pl.col("CF_GLASS_ID") != "NA",   
            pl.col("ARRAY_GLASS_ID") != "NA",   
        )
        .select("ARRAY_GLASS_ID", "CF_GLASS_ID")
        .unique()
        # .head()
        .write_excel(cwd / "tft_cf.xlsx")
)

In [60]:
(
    qtime_raw
        .filter(
            pl.col("COMPONENT_ID") == "611A2APB2HP212",
            pl.col('SUB_EQUIP_ID').str.contains(r"2CASM\d+"),
        )
        .head(20)
)

shape: (14, 42)
┌─────────────────┬──────────┬────────────────┬────────────────┬───┬────────────────┬────────────────┬──────────────┬──────┐
│ STEP_ID         ┆ STEP_SEQ ┆ GLASS_ID       ┆ COMPONENT_ID   ┆ … ┆ CHAMBER_TIME_P ┆ PI_REWORK_COUN ┆ REWORK_COUNT ┆ RN   │
│ ---             ┆ ---      ┆ ---            ┆ ---            ┆   ┆ ATH            ┆ T              ┆ ---          ┆ ---  │
│ str             ┆ i64      ┆ str            ┆ str            ┆   ┆ ---            ┆ ---            ┆ str          ┆ i64  │
│                 ┆          ┆                ┆                ┆   ┆ str            ┆ str            ┆              ┆      │
╞═════════════════╪══════════╪════════════════╪════════════════╪═══╪════════════════╪════════════════╪══════════════╪══════╡
│ 6310_AS1_ARC    ┆ 6310     ┆ 611A2APB2HP212 ┆ 611A2APB2HP212 ┆ … ┆                ┆                ┆              ┆ 982  │
│ 6310_AS1_ARC_BF ┆ 6310     ┆ 611A2APB2HP212 ┆ 611A2APB2HP212 ┆ … ┆                ┆                ┆              ┆ 1008 │
│ 6310_AS1_ARO    ┆ 6310     ┆ 611A2APB2HP212 ┆ 611A2APB2HP212 ┆ … ┆                ┆                ┆              ┆ 1034 │
│ 6310_AS1_LCD    ┆ 6310     ┆ 611A2APB2HP212 ┆ 611A2APB2HP212 ┆ … ┆ 20260122151439 ┆                ┆              ┆ 1060 │
│ 6310_AS1_LCI    ┆ 6310     ┆ 611A2APB2HP212 ┆ 611A2APB2HP212 ┆ … ┆ 20260122172427 ┆                ┆              ┆ 1086 │
│ 6310_AS1_LD     ┆ 6310     ┆ 611A2APB2HP212 ┆ 611A2APB2HP212 ┆ … ┆                ┆                ┆              ┆ 1112 │
│ 6310_AS1_ODF    ┆ 6310     ┆ 611A2APB2HP212 ┆ 611A2APB2HP212 ┆ … ┆ 20260122152024 ┆                ┆              ┆ 1138 │
│ 6310_AS1_SLD    ┆ 6310     ┆ 611A2APB2HP212 ┆ 611A2APB2HP212 ┆ … ┆                ┆                ┆              ┆ 1163 │
│ 6310_AS1_SLI_BF ┆ 6310     ┆ 611A2APB2HP212 ┆ 611A2APB2HP212 ┆ … ┆ 20260122150955 ┆                ┆              ┆ 1189 │
│ 6310_AS1_SMO    ┆ 6310     ┆ 611A2APB2HP212 ┆ 611A2APB2HP212 ┆ … ┆ 20260122162558 ┆                ┆              ┆ 1215 │
│                 ┆          ┆                ┆                ┆   ┆ ;2026012216305 ┆                ┆              ┆      │
│                 ┆          ┆                ┆                ┆   ┆ 7              ┆                ┆              ┆      │
│ 6310_AS1_TRD    ┆ 6310     ┆ 611A2APB2HP212 ┆ 611A2APB2HP212 ┆ … ┆ 20260122150113 ┆                ┆              ┆ 1241 │
│ 6310_AS1_ULD    ┆ 6310     ┆ 611A2APB2HP212 ┆ 611A2APB2HP212 ┆ … ┆                ┆                ┆              ┆ 1267 │
│ 6310_AS1_USC    ┆ 6310     ┆ 611A2APB2HP212 ┆ 611A2APB2HP212 ┆ … ┆ 20260122151141 ┆                ┆              ┆ 1293 │
│ 6310_AS1_UV_MA  ┆ 6310     ┆ 611A2APB2HP212 ┆ 611A2APB2HP212 ┆ … ┆ 20260122152252 ┆                ┆              ┆ 1319 │
│                 ┆          ┆                ┆                ┆   ┆ ;2026012215235 ┆                ┆              ┆      │
│                 ┆          ┆                ┆                ┆   ┆ 8              ┆                ┆              ┆      │
└─────────────────┴──────────┴────────────────┴────────────────┴───┴────────────────┴────────────────┴──────────────┴──────┘

In [63]:
def qtime_get(
    qtime_raw: pl.DataFrame, 
    step: tuple[str, str], 
    filter: list[pl.Expr] | None = None,
) -> pl.DataFrame:
    result = (
        qtime_raw.filter(
            pl.col("STEP_ID").str.contains(step),
        )
        .select(
            pl.col("GLASS_ID").alias("ID"), 
            pl.col("TRACK_IN_TIME"),
            pl.col("TRACK_OUT_TIME"),
        )
    )
    
    if filter is not None:
        return result.filter(*filter)
    
    return result

In [65]:
t2_qtime_steps = {
    "PIPB": {"step": "6110_PI2_PIC", "filter": None},
    "PAUV": {"step": "6220_PH3_PA_UV", "filter": None},
    "PAPB": {"step": "6220_PH3_OVEN", "filter": None},
    "BOOX": {"step": "6310_AS1_ARO", "filter": None},
    "ODFX": {"step": "6310_AS1_LCD", "filter": None},
    "SEUV": {"step": "6310_AS1_UV_MA", "filter": None},
}
qtime = qtime_raw.select(pl.col("GLASS_ID").alias("ID")).unique()
for step, kwargs in t2_qtime_steps.items():
    qtime = qtime.join(
        qtime_get(qtime_raw, **kwargs)
        .select(
            "ID",
            pl.col("TRACK_IN_TIME").alias(step + "_IN"),
            pl.col("TRACK_OUT_TIME").alias(step + "_OUT"),
        ),
        on='ID',
        how='left',
    )
qtime

shape: (52, 13)
┌──────────────┬──────────────┬──────────────┬──────────────┬───┬──────────────┬──────────────┬──────────────┬─────────────┐
│ ID           ┆ PIPB_IN      ┆ PIPB_OUT     ┆ PAUV_IN      ┆ … ┆ ODFX_IN      ┆ ODFX_OUT     ┆ SEUV_IN      ┆ SEUV_OUT    │
│ ---          ┆ ---          ┆ ---          ┆ ---          ┆   ┆ ---          ┆ ---          ┆ ---          ┆ ---         │
│ str          ┆ datetime[ms] ┆ datetime[ms] ┆ datetime[ms] ┆   ┆ datetime[ms] ┆ datetime[ms] ┆ datetime[ms] ┆ datetime[ms │
│              ┆              ┆              ┆              ┆   ┆              ┆              ┆              ┆ ]           │
╞══════════════╪══════════════╪══════════════╪══════════════╪═══╪══════════════╪══════════════╪══════════════╪═════════════╡
│ 611A2APB2HP2 ┆ 2026-01-21   ┆ 2026-01-21   ┆ 2026-01-22   ┆ … ┆ 2026-01-22   ┆ 2026-01-22   ┆ 2026-01-22   ┆ 2026-01-22  │
│ 18           ┆ 19:41:43     ┆ 19:43:16     ┆ 00:45:01     ┆   ┆ 15:58:30     ┆ 16:02:00     ┆ 16:07:07     ┆ 16:11:20    │
│ 611A2APB2HP2 ┆ 2026-01-21   ┆ 2026-01-21   ┆ 2026-01-22   ┆ … ┆ 2026-01-22   ┆ 2026-01-22   ┆ 2026-01-22   ┆ 2026-01-22  │
│ 25           ┆ 19:45:37     ┆ 19:47:11     ┆ 00:41:57     ┆   ┆ 21:45:25     ┆ 21:49:52     ┆ 21:56:31     ┆ 22:00:40    │
│ 611A2FPB2CBT ┆ 2026-01-21   ┆ 2026-01-21   ┆ 2026-01-22   ┆ … ┆ null         ┆ null         ┆ null         ┆ null        │
│ 25           ┆ 14:38:29     ┆ 14:40:02     ┆ 00:56:45     ┆   ┆              ┆              ┆              ┆             │
│ 611A2APB2HP2 ┆ 2026-01-21   ┆ 2026-01-21   ┆ 2026-01-22   ┆ … ┆ 2026-01-23   ┆ 2026-01-23   ┆ 2026-01-23   ┆ 2026-01-23  │
│ 02           ┆ 17:12:35     ┆ 17:14:08     ┆ 17:27:34     ┆   ┆ 21:41:06     ┆ 21:45:03     ┆ 21:50:12     ┆ 21:54:37    │
│ 611A2APB2HP2 ┆ 2026-01-21   ┆ 2026-01-21   ┆ 2026-01-22   ┆ … ┆ 2026-01-22   ┆ 2026-01-22   ┆ 2026-01-22   ┆ 2026-01-22  │
│ 13           ┆ 19:07:33     ┆ 19:09:06     ┆ 00:47:00     ┆   ┆ 11:53:51     ┆ 11:57:27     ┆ 12:02:35     ┆ 12:06:49    │
│ 611A2FPB2C8T ┆ 2026-01-21   ┆ 2026-01-21   ┆ 2026-01-22   ┆ … ┆ null         ┆ null         ┆ null         ┆ null        │
│ 35           ┆ 11:56:13     ┆ 11:57:36     ┆ 13:30:53     ┆   ┆              ┆              ┆              ┆             │
│ 611A2FPB2CET ┆ 2026-01-21   ┆ 2026-01-21   ┆ 2026-01-22   ┆ … ┆ null         ┆ null         ┆ null         ┆ null        │
│ 14           ┆ 14:28:04     ┆ 14:29:38     ┆ 01:01:49     ┆   ┆              ┆              ┆              ┆             │
│ 611A2APB2HP2 ┆ 2026-01-21   ┆ 2026-01-21   ┆ 2026-01-22   ┆ … ┆ 2026-01-22   ┆ 2026-01-22   ┆ 2026-01-22   ┆ 2026-01-22  │
│ 19           ┆ 19:42:22     ┆ 19:43:56     ┆ 00:44:04     ┆   ┆ 15:46:14     ┆ 15:49:03     ┆ 15:54:08     ┆ 15:58:22    │
│ 611A2APB2HP2 ┆ 2026-01-21   ┆ 2026-01-21   ┆ 2026-01-22   ┆ … ┆ 2026-01-23   ┆ 2026-01-23   ┆ 2026-01-23   ┆ 2026-01-23  │
│ 04           ┆ 17:13:14     ┆ 17:14:52     ┆ 13:38:05     ┆   ┆ 02:44:08     ┆ 02:47:27     ┆ 02:52:31     ┆ 02:56:43    │
│ 611A2APB2HP2 ┆ 2026-01-21   ┆ 2026-01-21   ┆ 2026-01-22   ┆ … ┆ 2026-01-22   ┆ 2026-01-22   ┆ 2026-01-22   ┆ 2026-01-22  │
│ 20           ┆ 19:43:01     ┆ 19:44:34     ┆ 00:46:01     ┆   ┆ 16:21:33     ┆ 16:25:14     ┆ 16:30:20     ┆ 16:35:55    │
│ 611A2APB2HP2 ┆ 2026-01-21   ┆ 2026-01-21   ┆ 2026-01-22   ┆ … ┆ 2026-01-22   ┆ 2026-01-22   ┆ 2026-01-22   ┆ 2026-01-22  │
│ 12           ┆ 19:06:54     ┆ 19:08:27     ┆ 00:47:31     ┆   ┆ 15:11:49     ┆ 15:15:20     ┆ 15:20:40     ┆ 15:24:53    │
│ 611A2APB2HP2 ┆ 2026-01-21   ┆ 2026-01-21   ┆ 2026-01-22   ┆ … ┆ 2026-01-22   ┆ 2026-01-22   ┆ 2026-01-22   ┆ 2026-01-22  │
│ 23           ┆ 19:44:59     ┆ 19:46:32     ┆ 00:42:19     ┆   ┆ 21:02:23     ┆ 21:05:35     ┆ 21:10:40     ┆ 21:14:54    │
│ 611A2FPB2CAT ┆ 2026-01-21   ┆ 2026-01-21   ┆ 2026-01-22   ┆ … ┆ null         ┆ null         ┆ null         ┆ null        │
│ 09           ┆ 14:33:56     ┆ 14:35:29     ┆ 01:00:53     ┆   ┆              ┆              ┆              ┆             │
│ 611A2FPB2CBT ┆ 2026-01-21   ┆ 2026-01-21   ┆ 2026-01-22   ┆ … ┆ null         ┆ null         ┆ null         ┆ null        │
│ 15           ┆ 14:35:14     ┆ 14:36:47     ┆ 01:00:31     ┆   ┆              ┆              ┆              ┆             │
│ 611A2FPB2CBT ┆ 2026-01-21   ┆ 2026-01-21   ┆ 2026-01-22   ┆ … ┆ null         ┆ null         ┆ null         ┆ null        │
│ 22           ┆ 14:35:53     ┆ 14:37:26     ┆ 00:59:07     ┆   ┆              ┆              ┆              ┆             │
│ 611A2APB2HP2 ┆ 2026-01-21   ┆ 2026-01-21   ┆ 2026-01-22   ┆ … ┆ 2026-01-23   ┆ 2026-01-23   ┆ 2026-01-23   ┆ 2026-01-23  │
│ 14           ┆ 19:08:12     ┆ 19:09:45     ┆ 13:37:33     ┆   ┆ 02:38:32     ┆ 02:41:34     ┆ 02:46:50     ┆ 02:51:03    │
│ 611A2FPB2C8T ┆ 2026-01-21   ┆ 2026-01-21   ┆ 2026-01-22   ┆ … ┆ null         ┆ null         ┆ null         ┆ null        │
│ 42           ┆ 09:49:12     ┆ 09:50:45     ┆ 18:18:33     ┆   ┆              ┆              ┆              ┆             │
│ 611A2FPB2CBT ┆ 2026-01-21   ┆ 2026-01-21   ┆ 2026-01-22   ┆ … ┆ null         ┆ null         ┆ null         ┆ null        │
│ 16           ┆ 14:32:38     ┆ 14:34:11     ┆ 01:03:19     ┆   ┆              ┆              ┆              ┆             │
│ 611A2APB2HP2 ┆ 2026-01-21   ┆ 2026-01-21   ┆ 2026-01-22   ┆ … ┆ 2026-01-22   ┆ 2026-01-22   ┆ 2026-01-22   ┆ 2026-01-22  │
│ 15           ┆ 19:08:51     ┆ 19:10:29     ┆ 00:46:31     ┆   ┆ 16:10:51     ┆ 16:13:58     ┆ 16:19:04     ┆ 16:24:50    │
│ 611A2APB2HP2 ┆ 2026-01-21   ┆ 2026-01-21   ┆ 2026-01-22   ┆ … ┆ 2026-01-22   ┆ 2026-01-22   ┆ 2026-01-22   ┆ 2026-01-22  │
│ 28           ┆ 19:47:35     ┆ 19:49:08     ┆ 00:40:29     ┆   ┆ 22:15:09     ┆ 22:18:28     ┆ 22:23:44     ┆ 22:28:05    │
│ 611A2FPB2CGT ┆ 2026-01-21   ┆ 2026-01-21   ┆ 2026-01-22   ┆ … ┆ null         ┆ null         ┆ null         ┆ null        │
│ 16           ┆ 14:37:11     ┆ 14:38:44     ┆ 00:57:58     ┆   ┆              ┆              ┆              ┆             │
│ 611A2FPB2C8T ┆ 2026-01-21   ┆ 2026-01-21   ┆ 2026-01-22   ┆ … ┆ null         ┆ null         ┆ null         ┆ null        │
│ 50           ┆ 09:51:09     ┆ 09:52:47     ┆ 17:54:54     ┆   ┆              ┆              ┆              ┆             │
│ 611A2APB2HP2 ┆ 2026-01-21   ┆ 2026-01-21   ┆ 2026-01-22   ┆ … ┆ 2026-01-22   ┆ 2026-01-22   ┆ 2026-01-22   ┆ 2026-01-22  │
│ 22           ┆ 19:44:20     ┆ 19:45:53     ┆ 00:42:50     ┆   ┆ 21:17:11     ┆ 21:20:30     ┆ 21:25:35     ┆ 21:29:54    │
│ 611A2FPB2CGT ┆ 2026-01-21   ┆ 2026-01-21   ┆ 2026-01-22   ┆ … ┆ null         ┆ null         ┆ null         ┆ null        │
│ 19           ┆ 14:27:25     ┆ 14:28:59     ┆ 11:17:53     ┆   ┆              ┆              ┆              ┆             │
│ 611A2FPB2CCT ┆ 2026-01-21   ┆ 2026-01-21   ┆ 2026-01-22   ┆ … ┆ null         ┆ null         ┆ null         ┆ null        │
│ 55           ┆ 14:39:08     ┆ 14:40:41     ┆ 00:57:16     ┆   ┆              ┆              ┆              ┆             │
│ 611A2APB2HP2 ┆ 2026-01-21   ┆ 2026-01-21   ┆ 2026-01-22   ┆ … ┆ 2026-01-23   ┆ 2026-01-23   ┆ 2026-01-23   ┆ 2026-01-23  │
│ 03           ┆ 15:38:17     ┆ 15:39:51     ┆ 18:12:47     ┆   ┆ 04:51:36     ┆ 04:54:39     ┆ 05:00:03     ┆ 05:04:19    │
│ 611A2APB2HP2 ┆ 2026-01-21   ┆ 2026-01-21   ┆ 2026-01-22   ┆ … ┆ 2026-01-23   ┆ 2026-01-23   ┆ 2026-01-23   ┆ 2026-01-23  │
│ 11           ┆ 19:06:15     ┆ 19:07:48     ┆ 11:12:50     ┆   ┆ 01:25:50     ┆ 01:30:02     ┆ 01:35:09     ┆ 01:39:28    │
│ 611A2APB2HP2 ┆ 2026-01-21   ┆ 2026-01-21   ┆ 2026-01-22   ┆ … ┆ 2026-01-22   ┆ 2026-01-22   ┆ 2026-01-22   ┆ 2026-01-22  │
│ 09           ┆ 19:50:11     ┆ 19:51:49     ┆ 00:22:39     ┆   ┆ 23:38:42     ┆ 23:41:56     ┆ 23:47:12     ┆ 23:51:25    │
│ 611A2FPB2CDT ┆ 2026-01-21   ┆ 2026-01-21   ┆ 2026-01-22   ┆ … ┆ null         ┆ null         ┆ null         ┆ null        │
│ 41           ┆ 12:59:39     ┆ 13:01:16     ┆ 13:30:22     ┆   ┆              ┆              ┆              ┆             │
│ 611A2FPB2CBT ┆ 2026-01-21   ┆ 2026-01-21   ┆ 2026-01-22   ┆ … ┆ null         ┆ null         ┆ null         ┆ null        │
│ 09           ┆ 14:31:59     ┆ 14:33:32     ┆ 00:31:28     ┆   ┆              ┆              ┆              ┆             │
│ 611A2FPB2CBT ┆ 2026-01-21   ┆ 2026-01-21   ┆ 2026-01-22   ┆ … ┆ null         ┆ null         ┆ null         ┆ null        │
│ 32           ┆ 14:30:02     ┆ 14:31:35     ┆ 11:18:25     ┆   ┆              ┆              ┆              ┆             │
│ 611A2FPB2CET ┆ 2026-01-21   ┆ 2026-01-21   ┆ 2026-01-22   ┆ … ┆ null         ┆ null         ┆ null         ┆ null        │
│ 07           ┆ 14:36:32     ┆ 14:38:05     ┆ 00:59:37     ┆   ┆              ┆              ┆              ┆             │
│ 611A2FPB2CCT ┆ 2026-01-21   ┆ 2026-01-21   ┆ 2026-01-22   ┆ … ┆ null         ┆ null         ┆ null         ┆ null        │
│ 50           ┆ 14:39:48     ┆ 14:41:25     ┆ 00:31:59     ┆   ┆              ┆              ┆              ┆             │
│ 611A2APB2HP2 ┆ 2026-01-21   ┆ 2026-01-21   ┆ 2026-01-22   ┆ … ┆ 2026-01-23   ┆ 2026-01-23   ┆ 2026-01-23   ┆ 2026-01-23  │
│ 05           ┆ 15:37:38     ┆ 15:39:12     ┆ 18:13:15     ┆   ┆ 04:52:53     ┆ 04:56:55     ┆ 05:02:03     ┆ 05:06:22    │
│ 611A2FPB2CDT ┆ 2026-01-21   ┆ 2026-01-21   ┆ 2026-01-22   ┆ … ┆ null         ┆ null         ┆ null         ┆ null        │
│ 47           ┆ 14:30:40     ┆ 14:32:14     ┆ 01:04:16     ┆   ┆              ┆              ┆              ┆             │
│ 611A2APB2HP2 ┆ 2026-01-21   ┆ 2026-01-21   ┆ 2026-01-22   ┆ … ┆ 2026-01-23   ┆ 2026-01-23   ┆ 2026-01-23   ┆ 2026-01-23  │
│ 01           ┆ 15:38:56     ┆ 15:40:34     ┆ 17:50:26     ┆   ┆ 21:39:37     ┆ 21:42:34     ┆ 21:47:59     ┆ 21:52:21    │
│ 611A2APB2HP2 ┆ 2026-01-21   ┆ 2026-01-21   ┆ 2026-01-22   ┆ … ┆ 2026-01-22   ┆ 2026-01-22   ┆ 2026-01-22   ┆ 2026-01-22  │
│ 26           ┆ 19:46:16     ┆ 19:47:50     ┆ 00:41:10     ┆   ┆ 21:44:08     ┆ 21:47:23     ┆ 21:52:31     ┆ 21:56:36    │
│ 611A2FPB2CET ┆ 2026-01-21   ┆ 2026-01-21   ┆ 2026-01-22   ┆ … ┆ null         ┆ null         ┆ null         ┆ null        │
│ 58           ┆ 14:33:17     ┆ 14:34:50     ┆ 01:02:19     ┆   ┆              ┆              ┆              ┆             │
│ 611A2APB2HP2 ┆ 2026-01-21   ┆ 2026-01-21   ┆ 2026-01-22   ┆ … ┆ 2026-01-22   ┆ 2026-01-22   ┆ 2026-01-22   ┆ 2026-01-22  │
│ 16           ┆ 19:41:04     ┆ 19:42:37     ┆ 00:45:32     ┆   ┆ 15:21:46     ┆ 15:25:05     ┆ 15:30:11     ┆ 15:34:25    │
│ 611A2FPB2CDT ┆ 2026-01-21   ┆ 2026-01-21   ┆ 2026-01-22   ┆ … ┆ null         ┆ null         ┆ null         ┆ null        │
│ 04           ┆ 14:37:50     ┆ 14:39:24     ┆ 00:58:45     ┆   ┆              ┆              ┆              ┆             │
│ 611A2FPB2C8T ┆ 2026-01-21   ┆ 2026-01-21   ┆ 2026-01-22   ┆ … ┆ null         ┆ null         ┆ null         ┆ null        │
│ 46           ┆ 14:31:20     ┆ 14:32:53     ┆ 01:02:48     ┆   ┆              ┆              ┆              ┆             │
│ 611A2FPB2CBT ┆ 2026-01-21   ┆ 2026-01-21   ┆ 2026-01-22   ┆ … ┆ null         ┆ null         ┆ null         ┆ null        │
│ 23           ┆ 14:28:43     ┆ 14:30:16     ┆ 01:00:01     ┆   ┆              ┆              ┆              ┆             │
│ 611A2FPB2CBT ┆ 2026-01-21   ┆ 2026-01-21   ┆ 2026-01-22   ┆ … ┆ null         ┆ null         ┆ null         ┆ null        │
│ 54           ┆ 09:49:51     ┆ 09:51:24     ┆ 18:18:04     ┆   ┆              ┆              ┆              ┆             │
│ 611A2APB2HP2 ┆ 2026-01-21   ┆ 2026-01-21   ┆ 2026-01-22   ┆ … ┆ 2026-01-22   ┆ 2026-01-22   ┆ 2026-01-22   ┆ 2026-01-22  │
│ 10           ┆ 19:48:14     ┆ 19:49:47     ┆ 00:23:10     ┆   ┆ 23:46:28     ┆ 23:49:52     ┆ 23:54:56     ┆ 23:59:09    │
│ 611A2APB2HP2 ┆ 2026-01-21   ┆ 2026-01-21   ┆ 2026-01-22   ┆ … ┆ 2026-01-22   ┆ 2026-01-22   ┆ 2026-01-22   ┆ 2026-01-22  │
│ 08           ┆ 19:49:32     ┆ 19:51:05     ┆ 00:43:12     ┆   ┆ 17:16:16     ┆ 18:18:48     ┆ 18:23:58     ┆ 18:28:11    │
│ 611A2APB2HP2 ┆ 2026-01-21   ┆ 2026-01-21   ┆ 2026-01-22   ┆ … ┆ 2026-01-22   ┆ 2026-01-22   ┆ 2026-01-22   ┆ 2026-01-22  │
│ 07           ┆ 19:48:53     ┆ 19:50:26     ┆ 00:44:35     ┆   ┆ 15:35:59     ┆ 15:39:18     ┆ 15:44:24     ┆ 15:48:37    │
│ 611A2FPB2C9T ┆ 2026-01-21   ┆ 2026-01-21   ┆ 2026-01-22   ┆ … ┆ null         ┆ null         ┆ null         ┆ null        │
│ 27           ┆ 14:29:23     ┆ 14:30:56     ┆ 01:03:47     ┆   ┆              ┆              ┆              ┆             │
│ 611A2FPB2CCT ┆ 2026-01-21   ┆ 2026-01-21   ┆ 2026-01-22   ┆ … ┆ null         ┆ null         ┆ null         ┆ null        │
│ 06           ┆ 09:50:30     ┆ 09:52:04     ┆ 17:55:22     ┆   ┆              ┆              ┆              ┆             │
│ 611A2APB2HP2 ┆ 2026-01-21   ┆ 2026-01-21   ┆ 2026-01-22   ┆ … ┆ 2026-01-22   ┆ 2026-01-22   ┆ 2026-01-22   ┆ 2026-01-22  │
│ 27           ┆ 19:46:55     ┆ 19:48:29     ┆ 00:39:57     ┆   ┆ 22:10:52     ┆ 22:13:40     ┆ 22:18:45     ┆ 22:23:07    │
│ 611A2FPB2CDT ┆ 2026-01-21   ┆ 2026-01-21   ┆ 2026-01-22   ┆ … ┆ null         ┆ null         ┆ null         ┆ null        │
│ 35           ┆ 14:34:35     ┆ 14:36:08     ┆ 01:01:23     ┆   ┆              ┆              ┆              ┆             │
│ 611A2APB2HP2 ┆ 2026-01-21   ┆ 2026-01-21   ┆ 2026-01-22   ┆ … ┆ 2026-01-23   ┆ 2026-01-23   ┆ 2026-01-23   ┆ 2026-01-23  │
│ 06           ┆ 19:05:35     ┆ 19:07:09     ┆ 11:13:22     ┆   ┆ 01:24:31     ┆ 01:27:34     ┆ 01:32:57     ┆ 01:37:14    │
│ 611A2APB2HP2 ┆ 2026-01-21   ┆ 2026-01-21   ┆ 2026-01-22   ┆ … ┆ 2026-01-22   ┆ 2026-01-22   ┆ 2026-01-22   ┆ 2026-01-22  │
│ 21           ┆ 19:43:40     ┆ 19:45:14     ┆ 00:43:42     ┆   ┆ 17:22:17     ┆ 18:21:10     ┆ 18:28:00     ┆ 18:32:13    │
└──────────────┴──────────────┴──────────────┴──────────────┴───┴──────────────┴──────────────┴──────────────┴─────────────┘

In [73]:
(
    condition
        .join(
            qtime.select([col for col in qtime.columns if qtime[col].null_count() == 0]),
            left_on="CF",
            right_on='ID',
            suffix="_CF",
            maintain_order="left",
        )
        .join(
            qtime,
            left_on="TFT",
            right_on="ID",
            suffix="_TFT",
            maintain_order="left",
        )
        .select(
            "Condition", "TFT", "CF",
            (pl.col('PAPB_IN'    ) - pl.col('PIPB_OUT'    )).alias('PIPB to PAPB - C'),
            (pl.col('PAPB_IN_TFT') - pl.col('PIPB_OUT_TFT')).alias('PIPB to PAPB - T'),
            (pl.col('BOOX_IN'    ) - pl.col('PAPB_OUT'    )).alias('PAPB to BOOX - C'),
            (pl.col('BOOX_IN'    ) - pl.col('PAPB_OUT_TFT')).alias('PAPB to BOOX - T'),
            # (pl.col('ODFX_IN'    ) - pl.col('LCDP_OUT'    )).alias('LCDP to ODFX'    ),
            (pl.col('SEUV_IN'    ) - pl.col('ODFX_OUT'    )).alias('ODFX to SEUV'    ),
        )
        # .write_excel(cwd / "qtime_summary.xlsx")
)

shape: (26, 8)
┌───────────────┬───────────────┬───────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┐
│ Condition     ┆ TFT           ┆ CF            ┆ PIPB to PAPB ┆ PIPB to PAPB ┆ PAPB to BOOX ┆ PAPB to BOOX ┆ ODFX to SEUV │
│ ---           ┆ ---           ┆ ---           ┆ - C          ┆ - T          ┆ - C          ┆ - T          ┆ ---          │
│ str           ┆ str           ┆ str           ┆ ---          ┆ ---          ┆ ---          ┆ ---          ┆ duration[ms] │
│               ┆               ┆               ┆ duration[ms] ┆ duration[ms] ┆ duration[ms] ┆ duration[ms] ┆              │
╞═══════════════╪═══════════════╪═══════════════╪══════════════╪══════════════╪══════════════╪══════════════╪══════════════╡
│ LC-1098       ┆ 611A2APB2HP22 ┆ 611A2FPB2CBT1 ┆ 10h 25m 47s  ┆ 5h 33s       ┆ 15h 27m 48s  ┆ 15h 44m 39s  ┆ 6m 50s       │
│               ┆ 1             ┆ 5             ┆              ┆              ┆              ┆              ┆              │
│ LC-1098       ┆ 611A2APB2HP20 ┆ 611A2FPB2CBT2 ┆ 10h 32m 18s  ┆ 4h 54m 42s   ┆ 15h 21m 10s  ┆ 15h 38m 1s   ┆ 5m 10s       │
│               ┆ 8             ┆ 3             ┆              ┆              ┆              ┆              ┆              │
│ STD-首件      ┆ 611A2APB2HP21 ┆ 611A2FPB2C9T2 ┆ 10h 35m 21s  ┆ 5h 40m 26s   ┆ 9h 47m 35s   ┆ 10h 4m 19s   ┆ 5m 8s        │
│               ┆ 3             ┆ 7             ┆              ┆              ┆              ┆              ┆              │
│ STD           ┆ 611A2APB2HP21 ┆ 611A2FPB2CDT4 ┆ 10h 34m 3s   ┆ 5h 41m 5s    ┆ 13h 9m 12s   ┆ 13h 25m 56s  ┆ 5m 20s       │
│               ┆ 2             ┆ 7             ┆              ┆              ┆              ┆              ┆              │
│ STD           ┆ 611A2APB2HP21 ┆ 611A2FPB2CET5 ┆ 10h 29m 39s  ┆ 5h 5m 6s     ┆ 13h 17m 36s  ┆ 13h 34m 24s  ┆ 5m 6s        │
│               ┆ 6             ┆ 8             ┆              ┆              ┆              ┆              ┆              │
│ PAUV 260      ┆ 611A2APB2HP20 ┆ 611A2FPB2C8T3 ┆ 1d 1h 35m    ┆ 20h 32m 46s  ┆ 12h 13m 41s  ┆ 11h 58m 56s  ┆ 5m 4s        │
│               ┆ 4             ┆ 5             ┆ 22s          ┆              ┆              ┆              ┆              │
│ PAUV 260      ┆ 611A2APB2HP21 ┆ 611A2FPB2CDT4 ┆ 1d 31m 42s   ┆ 18h 31m 16s  ┆ 12h 7m 5s    ┆ 11h 59m 7s   ┆ 5m 16s       │
│               ┆ 4             ┆ 1             ┆              ┆              ┆              ┆              ┆              │
│ PAUV 220      ┆ 611A2APB2HP20 ┆ 611A2FPB2CGT1 ┆ 20h 52m 2s   ┆ 16h 8m 14s   ┆ 12h 58m 22s  ┆ 13h 4m       ┆ 5m 23s       │
│               ┆ 6             ┆ 9             ┆              ┆              ┆              ┆              ┆              │
│ PAUV 220      ┆ 611A2APB2HP21 ┆ 611A2FPB2CBT3 ┆ 20h 49m 26s  ┆ 16h 7m 35s   ┆ 13h 5m 37s   ┆ 13h 11m 15s  ┆ 5m 7s        │
│               ┆ 1             ┆ 2             ┆              ┆              ┆              ┆              ┆              │
│ 24 + 24       ┆ 611A2APB2HP20 ┆ 611A2FPB2C8T5 ┆ 1d 8h 4m 54s ┆ 1d 2h 13m 4s ┆ 1d 2h 31m    ┆ 1d 2h 35m    ┆ 5m 25s       │
│               ┆ 1             ┆ 0             ┆              ┆              ┆ 48s          ┆ 57s          ┆              │
│ 24 + 24       ┆ 611A2APB2HP20 ┆ 611A2FPB2CCT0 ┆ 1d 8h 5m 37s ┆ 1d 16m 49s   ┆ 1d 2h 38m    ┆ 1d 3h 5m 15s ┆ 5m 9s        │
│               ┆ 2             ┆ 6             ┆              ┆              ┆ 24s          ┆              ┆              │
│ PAPB to ARO   ┆ 611A2APB2HP20 ┆ 611A2FPB2CBT0 ┆ 10h 1m 5s    ┆ 4h 34m       ┆ 22h 12m 12s  ┆ 22h 21m 3s   ┆ 5m 16s       │
│ 24 hr         ┆ 9             ┆ 9             ┆              ┆              ┆              ┆              ┆              │
│ PAPB to ARO   ┆ 611A2APB2HP21 ┆ 611A2FPB2CCT5 ┆ 9h 53m 12s   ┆ 4h 36m 2s    ┆ 22h 18m 47s  ┆ 22h 27m 38s  ┆ 5m 4s        │
│ 24 hr         ┆ 0             ┆ 0             ┆              ┆              ┆              ┆              ┆              │
│ PIPB to PAPB  ┆ 611A2APB2HP20 ┆ 611A2FPB2C8T4 ┆ 1d 8h 30m 6s ┆ 1d 2h 36m    ┆ 9h 7m 11s    ┆ 9h 12m 25s   ┆ 5m 8s        │
│ 24 hr         ┆ 5             ┆ 2             ┆              ┆ 22s          ┆              ┆              ┆              │
│ PIPB to PAPB  ┆ 611A2APB2HP20 ┆ 611A2FPB2CBT5 ┆ 1d 8h 29m    ┆ 1d 2h 35m    ┆ 9h 13m 46s   ┆ 9h 19m       ┆ 5m 24s       │
│ 24 hr         ┆ 3             ┆ 4             ┆ 27s          ┆ 43s          ┆              ┆              ┆              │
│ ODF to SEUV   ┆ 611A2APB2HP21 ┆ 611A2FPB2CBT1 ┆ 10h 31m 16s  ┆ 5h 38m 13s   ┆ 13h 45m 27s  ┆ 14h 2m 14s   ┆ 5m 6s        │
│ 150 s         ┆ 5             ┆ 6             ┆              ┆              ┆              ┆              ┆              │
│ ODF to SEUV   ┆ 611A2APB2HP22 ┆ 611A2FPB2C8T4 ┆ 10h 32m 34s  ┆ 5h 4m 8s     ┆ 13h 55m 19s  ┆ 14h 12m 6s   ┆ 5m 6s        │
│ 150 s         ┆ 0             ┆ 6             ┆              ┆              ┆              ┆              ┆              │
│ ODF 加抽 95 s ┆ 611A2APB2HP21 ┆ 611A2FPB2CET1 ┆ 10h 34m 51s  ┆ 5h 4m 27s    ┆ 13h 37m 24s  ┆ 13h 54m 12s  ┆ 5m 7s        │
│               ┆ 8             ┆ 4             ┆              ┆              ┆              ┆              ┆              │
│ ODF 加抽 65 s ┆ 611A2APB2HP20 ┆ 611A2FPB2CDT3 ┆ 10h 27m 22s  ┆ 4h 56m 18s   ┆ 13h 25m 11s  ┆ 13h 41m 59s  ┆ 5m 6s        │
│               ┆ 7             ┆ 5             ┆              ┆              ┆              ┆              ┆              │
│ ODF 加抽 65 s ┆ 611A2APB2HP21 ┆ 611A2FPB2CAT0 ┆ 10h 28m 1s   ┆ 5h 2m 48s    ┆ 13h 31m 47s  ┆ 13h 48m 35s  ┆ 5m 5s        │
│               ┆ 9             ┆ 9             ┆              ┆              ┆              ┆              ┆              │
│ ARO to ODF 60 ┆ 611A2APB2HP22 ┆ 611A2FPB2CBT2 ┆ 10h 24m 15s  ┆ 4h 59m 1s    ┆ 18h 20m 12s  ┆ 18h 37m 3s   ┆ 5m 5s        │
│ min           ┆ 2             ┆ 2             ┆              ┆              ┆              ┆              ┆              │
│ ARO to ODF 60 ┆ 611A2APB2HP22 ┆ 611A2FPB2CET0 ┆ 10h 23m 36s  ┆ 4h 58m 22s   ┆ 18h 9m 38s   ┆ 18h 26m 29s  ┆ 5m 5s        │
│ min           ┆ 3             ┆ 7             ┆              ┆              ┆              ┆              ┆              │
│ SEUV 5000     ┆ 611A2APB2HP22 ┆ 611A2FPB2CDT0 ┆ 10h 21m 25s  ┆ 4h 56m 52s   ┆ 19h 46m 19s  ┆ 20h 3m 8s    ┆ 6m 39s       │
│               ┆ 5             ┆ 4             ┆              ┆              ┆              ┆              ┆              │
│ SEUV 5000     ┆ 611A2APB2HP22 ┆ 611A2FPB2CGT1 ┆ 10h 22m 5s   ┆ 4h 56m 13s   ┆ 19h 39m 43s  ┆ 19h 56m 32s  ┆ 5m 8s        │
│               ┆ 6             ┆ 6             ┆              ┆              ┆              ┆              ┆              │
│ SEUV 7000     ┆ 611A2APB2HP22 ┆ 611A2FPB2CBT2 ┆ 10h 19m 55s  ┆ 4h 54m 40s   ┆ 20h 17m 7s   ┆ 20h 33m 56s  ┆ 5m 5s        │
│               ┆ 7             ┆ 5             ┆              ┆              ┆              ┆              ┆              │
│ SEUV 7000     ┆ 611A2APB2HP22 ┆ 611A2FPB2CCT5 ┆ 10h 19m 16s  ┆ 4h 54m 1s    ┆ 20h 23m 43s  ┆ 20h 40m 32s  ┆ 5m 16s       │
│               ┆ 8             ┆ 5             ┆              ┆              ┆              ┆              ┆              │
└───────────────┴───────────────┴───────────────┴──────────────┴──────────────┴──────────────┴──────────────┴──────────────┘

PI prebake 溫度, 時間  
PI postbake 溫度, 時間  
PAUV dosage  
PAPB 溫度, 時間  
ARO 溫度, 時間  
SEUV dosage  
SMO 溫度, 時間