In [3]:
%load_ext autoreload
%autoreload 2
from innolux import *

In [4]:
# set polars show all rows
pl.Config.set_tbl_rows(-1)

polars.config.Config

In [5]:
cwd = data_path / "T2 6117" / "pds"

In [6]:
cwd

WindowsPath('D:/Documents/Projects/innolux/data/T2 6117/pds')

In [7]:
def edc_get(
    edc_raw: pl.DataFrame, 
    step: tuple[str, str], 
    filter: list[pl.Expr] | None = None,
) -> pl.DataFrame:
    result = (
        edc_raw.filter(
            pl.col("SUB_EQUIP_ID").str.contains(step[0]),
            pl.col("PARAM_NAME").str.contains(step[1])
        )
        # .select(
        #     "GLASS_ID", "SUB_EQUIP_ID", "PARAM_NAME", "AVG_VALUE"
        # )
        .select(
            "ID", 
            pl.col("PARAM_VALUE").cast(float)
        )
    )
    
    if filter is not None:
        result = result.filter(*filter)
    
    return result.group_by(['ID']).mean()

In [8]:
# lf - lazy data frame
eda_lf = pl.scan_csv(cwd / "pds-*.csv", ignore_errors=True)
eda_raw = (
    eda_lf
        .with_columns(
            pl.col("PARAM_VALUE")
                .cast(float, strict=False)
                .fill_null(0),
            pl.col("GLASS_ID").alias("ID"),
        )
        .filter(pl.col("PARAM_VALUE") > 0)
        .collect()
)

In [9]:
condition = pl.read_excel(cwd / "condition.xlsx")

In [10]:
condition

shape: (26, 3)
┌────────────────────┬────────────────┬────────────────┐
│ Condition          ┆ TFT            ┆ CF             │
│ ---                ┆ ---            ┆ ---            │
│ str                ┆ str            ┆ str            │
╞════════════════════╪════════════════╪════════════════╡
│ LC-1098            ┆ 611A2APB2HP221 ┆ 611A2FPB2CBT15 │
│ LC-1098            ┆ 611A2APB2HP208 ┆ 611A2FPB2CBT23 │
│ STD-首件           ┆ 611A2APB2HP213 ┆ 611A2FPB2C9T27 │
│ STD                ┆ 611A2APB2HP212 ┆ 611A2FPB2CDT47 │
│ STD                ┆ 611A2APB2HP216 ┆ 611A2FPB2CET58 │
│ PAUV 260           ┆ 611A2APB2HP204 ┆ 611A2FPB2C8T35 │
│ PAUV 260           ┆ 611A2APB2HP214 ┆ 611A2FPB2CDT41 │
│ PAUV 220           ┆ 611A2APB2HP206 ┆ 611A2FPB2CGT19 │
│ PAUV 220           ┆ 611A2APB2HP211 ┆ 611A2FPB2CBT32 │
│ 24 + 24            ┆ 611A2APB2HP201 ┆ 611A2FPB2C8T50 │
│ 24 + 24            ┆ 611A2APB2HP202 ┆ 611A2FPB2CCT06 │
│ PAPB to ARO 24 hr  ┆ 611A2APB2HP209 ┆ 611A2FPB2CBT09 │
│ PAPB to ARO 24 hr  ┆ 611A2APB2HP210 ┆ 611A2FPB2CCT50 │
│ PIPB to PAPB 24 hr ┆ 611A2APB2HP205 ┆ 611A2FPB2C8T42 │
│ PIPB to PAPB 24 hr ┆ 611A2APB2HP203 ┆ 611A2FPB2CBT54 │
│ ODF to SEUV 150 s  ┆ 611A2APB2HP215 ┆ 611A2FPB2CBT16 │
│ ODF to SEUV 150 s  ┆ 611A2APB2HP220 ┆ 611A2FPB2C8T46 │
│ ODF 加抽 95 s      ┆ 611A2APB2HP218 ┆ 611A2FPB2CET14 │
│ ODF 加抽 65 s      ┆ 611A2APB2HP207 ┆ 611A2FPB2CDT35 │
│ ODF 加抽 65 s      ┆ 611A2APB2HP219 ┆ 611A2FPB2CAT09 │
│ ARO to ODF 60 min  ┆ 611A2APB2HP222 ┆ 611A2FPB2CBT22 │
│ ARO to ODF 60 min  ┆ 611A2APB2HP223 ┆ 611A2FPB2CET07 │
│ SEUV 5000          ┆ 611A2APB2HP225 ┆ 611A2FPB2CDT04 │
│ SEUV 5000          ┆ 611A2APB2HP226 ┆ 611A2FPB2CGT16 │
│ SEUV 7000          ┆ 611A2APB2HP227 ┆ 611A2FPB2CBT25 │
│ SEUV 7000          ┆ 611A2APB2HP228 ┆ 611A2FPB2CCT55 │
└────────────────────┴────────────────┴────────────────┘

In [111]:
eda_lf.filter(pl.col("SUB_EQUIP_ID").str.contains(r"2CPHA340")).head().collect()

shape: (5, 36)
┌────────────────┬────────────────┬─────────────────────┬─────────────────────┬───┬───────┬─────────────────┬─────┬──────┐
│ STEP_ID        ┆ GLASS_ID       ┆ PROCESS_START_TIME  ┆ PROCESS_END_TIME    ┆ … ┆ COUNT ┆ PARAM_STR_VALUE ┆ RN  ┆      │
│ ---            ┆ ---            ┆ ---                 ┆ ---                 ┆   ┆ ---   ┆ ---             ┆ --- ┆ ---  │
│ str            ┆ str            ┆ str                 ┆ str                 ┆   ┆ str   ┆ str             ┆ i64 ┆ str  │
╞════════════════╪════════════════╪═════════════════════╪═════════════════════╪═══╪═══════╪═════════════════╪═════╪══════╡
│ 6220_PH3_PA_UV ┆ 611A2APB2HP201 ┆ 2026/01/22 17:23:43 ┆ 2026/01/22 17:50:26 ┆ … ┆       ┆                 ┆ 1   ┆ null │
│ 6220_PH3_PA_UV ┆ 611A2APB2HP201 ┆ 2026/01/22 17:23:43 ┆ 2026/01/22 17:50:26 ┆ … ┆       ┆                 ┆ 2   ┆ null │
│ 6220_PH3_PA_UV ┆ 611A2APB2HP201 ┆ 2026/01/22 17:23:43 ┆ 2026/01/22 17:50:26 ┆ … ┆       ┆                 ┆ 3   ┆ null │
│ 6220_PH3_PA_UV ┆ 611A2APB2HP201 ┆ 2026/01/22 17:23:43 ┆ 2026/01/22 17:50:26 ┆ … ┆       ┆                 ┆ 4   ┆ null │
│ 6220_PH3_PA_UV ┆ 611A2APB2HP201 ┆ 2026/01/22 17:23:43 ┆ 2026/01/22 17:50:26 ┆ … ┆       ┆                 ┆ 5   ┆ null │
└────────────────┴────────────────┴─────────────────────┴─────────────────────┴───┴───────┴─────────────────┴─────┴──────┘

In [20]:
pauv_df = (
    eda_raw
        .filter(
            # pl.col("ID") == "611A2APB2HP225",
            pl.col("SUB_EQUIP_ID").str.contains(r"2CPHA\d+"),
            pl.col("PARAM_NAME").str.contains(r"\d-\d exposure"),
            # pl.col("PARAM_NAME").str.contains(r"Oven_\d_Temp\d"),
            # pl.col("PARAM_VALUE").is_between(500,700),
        )
        .select(
            "ID", 
            "SUB_EQUIP_ID",
            "PARAM_NAME",
            "PARAM_VALUE"
        )
        # .slice(110,20)
        .group_by("ID")
        .agg("PARAM_VALUE")
        .with_columns(pl.col("PARAM_VALUE").list.to_struct(fields=["PAUV-1", "PAUV-2", "PAUV-3"]))
        .unnest("PARAM_VALUE")
)

In [25]:
(condition
    .join(
        pauv_df.select([col for col in pauv_df.columns if pauv_df[col].null_count() == 0]),
        left_on="CF",
        right_on='ID',
        suffix="_CF",
        maintain_order="left",
    )
    .join(
        pauv_df,
        left_on="TFT",
        right_on="ID",
        suffix=" - T",
        maintain_order="left",
    )
    .select(
        pl.col('Condition'),
        pl.col('TFT'),
        pl.col('CF'),
        pl.col('PAUV-1 - T'),
        pl.col('PAUV-2 - T'),
        pl.col('PAUV-3 - T'),
        pl.col('PAUV-1').alias('PAUV-1 - C'),
        pl.col('PAUV-2').alias('PAUV-2 - C'),
        pl.col('PAUV-3').alias('PAUV-3 - C'),
    )
    .write_excel(cwd / "eda_pauv.xlsx")
)

In [29]:
(
    eda_raw
        .filter(
            pl.col("ID") == "611A2APB2HP225",
            pl.col("SUB_EQUIP_ID").str.contains(r"2CASM"),
            pl.col("PARAM_NAME").str.contains(r"(?i)qtime"),
            # pl.col("PARAM_NAME").str.contains(r"Oven_\d_Temp\d"),
            # pl.col("PARAM_VALUE").is_between(500,700),
        )
        .select(
            "ID", 
            "SUB_EQUIP_ID",
            "PARAM_NAME",
            "PARAM_VALUE",
        )
)

shape: (3, 4)
┌────────────────┬──────────────┬────────────────┬─────────────┐
│ ID             ┆ SUB_EQUIP_ID ┆ PARAM_NAME     ┆ PARAM_VALUE │
│ ---            ┆ ---          ┆ ---            ┆ ---         │
│ str            ┆ str          ┆ str            ┆ f64         │
╞════════════════╪══════════════╪════════════════╪═════════════╡
│ 611A2APB2HP225 ┆ 2CASM1B0     ┆ ARO_ODF_QTime  ┆ 1938.0      │
│ 611A2APB2HP225 ┆ 2CASM1C0     ┆ ODFIN_UV_QTime ┆ 307.0       │
│ 611A2APB2HP225 ┆ 2CASM1C0     ┆ ODF_UV_QTime   ┆ 68.0        │
└────────────────┴──────────────┴────────────────┴─────────────┘

In [30]:
t2_edc_steps = {
    "PIPR TEMP": {"step": (r"2CPIL\d+", r"PreCur\d+_temp"), "filter": None},
    "PIPR TIME": {"step": (r"2CPIL\d+", r"PreCur\d+_Time"), "filter": None},
    "PIPB TEMP": {"step": (r"2CPIL\d+", r"Oven_Temp_\d+"), "filter": None},
    "PIPB TIME": {"step": (r"2CPIL\d+", r"Heating_Time"), "filter": None},
    "PAUV": {"step": (r"2CPHA\d+", r"\d-\d exposure"), "filter": None},
    "PAPB TEMP": {"step": (r"2CPHA\d+", r"Baking temp zone\d+"), "filter": None},
    "PAPB TIME": {"step": (r"2CPHA\d+", r"Heating_Time"), "filter": None},
    "BOOX TEMP": {"step": (r"2CASM\d+", r"Oven_Temp_\d+"), "filter": None},
    "BOOX TIME": {"step": (r"2CASM\d30", r"Heating_Time"), "filter": None},
    "SEUV": {"step": (r"2CASM\dC0", r"UV_Energy"), "filter": None},
    "SEPB TEMP": {"step": (r"2CASM\dD0", r"Temp"), "filter": None},
    "SEPB TIME" : {"step": (r"2CASM\dD0", r"Heating_Time"), "filter": None},
    "BOOX to ODF" : {"step": (r"2CASM\dB0", r"ARO_ODF_QTime"), "filter": None},
    "ODF to SEUV" : {"step": (r"2CASM\dC0", r"ODF_UV_QTime"), "filter": None},
}
eda = eda_raw.select("ID").unique()
for step, kwargs in t2_edc_steps.items():
    eda = eda.join(
        edc_get(eda_raw, **kwargs)
        .select(
            "ID",
            pl.col("PARAM_VALUE").alias(step),
        ),
        on='ID',
        how='left',
    )
eda

shape: (52, 15)
┌─────────────┬───────────┬───────────┬────────────┬───┬───────────┬───────────┬─────────────┬─────────────┐
│ ID          ┆ PIPR TEMP ┆ PIPR TIME ┆ PIPB TEMP  ┆ … ┆ SEPB TEMP ┆ SEPB TIME ┆ BOOX to ODF ┆ ODF to SEUV │
│ ---         ┆ ---       ┆ ---       ┆ ---        ┆   ┆ ---       ┆ ---       ┆ ---         ┆ ---         │
│ str         ┆ f64       ┆ f64       ┆ f64        ┆   ┆ f64       ┆ f64       ┆ f64         ┆ f64         │
╞═════════════╪═══════════╪═══════════╪════════════╪═══╪═══════════╪═══════════╪═════════════╪═════════════╡
│ 611A2FPB2CA ┆ 135.0     ┆ 80.0      ┆ 210.9      ┆ … ┆ null      ┆ null      ┆ null        ┆ null        │
│ T09         ┆           ┆           ┆            ┆   ┆           ┆           ┆             ┆             │
│ 611A2FPB2CB ┆ 135.0     ┆ 80.0      ┆ 210.666667 ┆ … ┆ null      ┆ null      ┆ null        ┆ null        │
│ T16         ┆           ┆           ┆            ┆   ┆           ┆           ┆             ┆             │
│ 611A2APB2HP ┆ 135.0     ┆ 80.0      ┆ 210.316667 ┆ … ┆ 119.98    ┆ 3647.0    ┆ 2319.0      ┆ 69.0        │
│ 207         ┆           ┆           ┆            ┆   ┆           ┆           ┆             ┆             │
│ 611A2APB2HP ┆ 135.0     ┆ 80.0      ┆ 210.8      ┆ … ┆ 120.0     ┆ 3648.0    ┆ 1862.0      ┆ 68.0        │
│ 216         ┆           ┆           ┆            ┆   ┆           ┆           ┆             ┆             │
│ 611A2FPB2C9 ┆ 135.0     ┆ 80.0      ┆ 210.633333 ┆ … ┆ null      ┆ null      ┆ null        ┆ null        │
│ T27         ┆           ┆           ┆            ┆   ┆           ┆           ┆             ┆             │
│ 611A2APB2HP ┆ 135.0     ┆ 80.0      ┆ 210.966667 ┆ … ┆ 120.0     ┆ 3648.0    ┆ 1897.0      ┆ 69.0        │
│ 213         ┆           ┆           ┆            ┆   ┆           ┆           ┆             ┆             │
│ 611A2APB2HP ┆ 135.0     ┆ 80.0      ┆ 210.766667 ┆ … ┆ 119.96    ┆ 3648.0    ┆ 5198.0      ┆ 69.0        │
│ 222         ┆           ┆           ┆            ┆   ┆           ┆           ┆             ┆             │
│ 611A2APB2HP ┆ 135.0     ┆ 80.0      ┆ 210.633333 ┆ … ┆ 119.98    ┆ 3648.0    ┆ 2507.0      ┆ 69.0        │
│ 219         ┆           ┆           ┆            ┆   ┆           ┆           ┆             ┆             │
│ 611A2APB2HP ┆ 135.0     ┆ 80.0      ┆ 210.366667 ┆ … ┆ 120.0     ┆ 3649.0    ┆ 1382.0      ┆ 70.0        │
│ 209         ┆           ┆           ┆            ┆   ┆           ┆           ┆             ┆             │
│ 611A2APB2HP ┆ 135.0     ┆ 80.0      ┆ 210.866667 ┆ … ┆ 120.0     ┆ 3673.0    ┆ 1726.0      ┆ 69.0        │
│ 204         ┆           ┆           ┆            ┆   ┆           ┆           ┆             ┆             │
│ 611A2FPB2C8 ┆ 135.0     ┆ 80.0      ┆ 210.666667 ┆ … ┆ null      ┆ null      ┆ null        ┆ null        │
│ T46         ┆           ┆           ┆            ┆   ┆           ┆           ┆             ┆             │
│ 611A2FPB2CD ┆ 135.0     ┆ 80.0      ┆ 211.0      ┆ … ┆ null      ┆ null      ┆ null        ┆ null        │
│ T04         ┆           ┆           ┆            ┆   ┆           ┆           ┆             ┆             │
│ 611A2FPB2CD ┆ 135.0     ┆ 80.0      ┆ 210.9      ┆ … ┆ null      ┆ null      ┆ null        ┆ null        │
│ T35         ┆           ┆           ┆            ┆   ┆           ┆           ┆             ┆             │
│ 611A2FPB2CB ┆ 135.0     ┆ 80.0      ┆ 210.633333 ┆ … ┆ null      ┆ null      ┆ null        ┆ null        │
│ T54         ┆           ┆           ┆            ┆   ┆           ┆           ┆             ┆             │
│ 611A2APB2HP ┆ 135.0     ┆ 80.0      ┆ 211.033333 ┆ … ┆ 119.86    ┆ 3654.0    ┆ 1671.0      ┆ 69.0        │
│ 212         ┆           ┆           ┆            ┆   ┆           ┆           ┆             ┆             │
│ 611A2FPB2CB ┆ 135.0     ┆ 80.0      ┆ 210.833333 ┆ … ┆ null      ┆ null      ┆ null        ┆ null        │
│ T23         ┆           ┆           ┆            ┆   ┆           ┆           ┆             ┆             │
│ 611A2APB2HP ┆ 135.0     ┆ 80.0      ┆ 210.8      ┆ … ┆ 120.04    ┆ 3649.0    ┆ 3149.0      ┆ 146.0       │
│ 220         ┆           ┆           ┆            ┆   ┆           ┆           ┆             ┆             │
│ 611A2FPB2CG ┆ 135.0     ┆ 80.0      ┆ 210.766667 ┆ … ┆ null      ┆ null      ┆ null        ┆ null        │
│ T19         ┆           ┆           ┆            ┆   ┆           ┆           ┆             ┆             │
│ 611A2FPB2CB ┆ 135.0     ┆ 80.0      ┆ 210.8      ┆ … ┆ null      ┆ null      ┆ null        ┆ null        │
│ T09         ┆           ┆           ┆            ┆   ┆           ┆           ┆             ┆             │
│ 611A2FPB2CC ┆ 135.0     ┆ 80.0      ┆ 210.516667 ┆ … ┆ null      ┆ null      ┆ null        ┆ null        │
│ T55         ┆           ┆           ┆            ┆   ┆           ┆           ┆             ┆             │
│ 611A2APB2HP ┆ 135.0     ┆ 80.0      ┆ 210.35     ┆ … ┆ 120.02    ┆ 3649.0    ┆ 4985.0      ┆ 73.0        │
│ 208         ┆           ┆           ┆            ┆   ┆           ┆           ┆             ┆             │
│ 611A2APB2HP ┆ 135.0     ┆ 80.0      ┆ 210.7      ┆ … ┆ 120.02    ┆ 3648.0    ┆ 2093.0      ┆ 73.0        │
│ 226         ┆           ┆           ┆            ┆   ┆           ┆           ┆             ┆             │
│ 611A2FPB2CD ┆ 135.0     ┆ 80.0      ┆ 211.0      ┆ … ┆ null      ┆ null      ┆ null        ┆ null        │
│ T41         ┆           ┆           ┆            ┆   ┆           ┆           ┆             ┆             │
│ 611A2APB2HP ┆ 135.0     ┆ 80.0      ┆ 210.733333 ┆ … ┆ 119.98    ┆ 3648.0    ┆ 4831.0      ┆ 68.0        │
│ 221         ┆           ┆           ┆            ┆   ┆           ┆           ┆             ┆             │
│ 611A2FPB2CC ┆ 135.0     ┆ 80.0      ┆ 210.483333 ┆ … ┆ null      ┆ null      ┆ null        ┆ null        │
│ T50         ┆           ┆           ┆            ┆   ┆           ┆           ┆             ┆             │
│ 611A2FPB2C8 ┆ 135.0     ┆ 80.0      ┆ 210.633333 ┆ … ┆ null      ┆ null      ┆ null        ┆ null        │
│ T42         ┆           ┆           ┆            ┆   ┆           ┆           ┆             ┆             │
│ 611A2FPB2CC ┆ 135.0     ┆ 80.0      ┆ 210.533333 ┆ … ┆ null      ┆ null      ┆ null        ┆ null        │
│ T06         ┆           ┆           ┆            ┆   ┆           ┆           ┆             ┆             │
│ 611A2FPB2CB ┆ 135.0     ┆ 80.0      ┆ 210.516667 ┆ … ┆ null      ┆ null      ┆ null        ┆ null        │
│ T25         ┆           ┆           ┆            ┆   ┆           ┆           ┆             ┆             │
│ 611A2FPB2CB ┆ 135.0     ┆ 80.0      ┆ 210.766667 ┆ … ┆ null      ┆ null      ┆ null        ┆ null        │
│ T32         ┆           ┆           ┆            ┆   ┆           ┆           ┆             ┆             │
│ 611A2FPB2CE ┆ 135.0     ┆ 80.0      ┆ 210.666667 ┆ … ┆ null      ┆ null      ┆ null        ┆ null        │
│ T14         ┆           ┆           ┆            ┆   ┆           ┆           ┆             ┆             │
│ 611A2APB2HP ┆ 135.0     ┆ 80.0      ┆ 210.9      ┆ … ┆ 120.0     ┆ 3649.0    ┆ 2879.0      ┆ 70.0        │
│ 203         ┆           ┆           ┆            ┆   ┆           ┆           ┆             ┆             │
│ 611A2APB2HP ┆ 135.0     ┆ 80.0      ┆ 210.966667 ┆ … ┆ 120.0     ┆ 3649.0    ┆ 3065.0      ┆ 161.0       │
│ 215         ┆           ┆           ┆            ┆   ┆           ┆           ┆             ┆             │
│ 611A2FPB2CB ┆ 135.0     ┆ 80.0      ┆ 211.0      ┆ … ┆ null      ┆ null      ┆ null        ┆ null        │
│ T22         ┆           ┆           ┆            ┆   ┆           ┆           ┆             ┆             │
│ 611A2APB2HP ┆ 135.0     ┆ 80.0      ┆ 210.9      ┆ … ┆ 119.96    ┆ 3647.0    ┆ 2216.0      ┆ 70.0        │
│ 202         ┆           ┆           ┆            ┆   ┆           ┆           ┆             ┆             │
│ 611A2APB2HP ┆ 135.0     ┆ 80.0      ┆ 210.733333 ┆ … ┆ 120.04    ┆ 3647.0    ┆ 2889.0      ┆ 70.0        │
│ 218         ┆           ┆           ┆            ┆   ┆           ┆           ┆             ┆             │
│ 611A2FPB2CE ┆ 135.0     ┆ 80.0      ┆ 210.666667 ┆ … ┆ null      ┆ null      ┆ null        ┆ null        │
│ T58         ┆           ┆           ┆            ┆   ┆           ┆           ┆             ┆             │
│ 611A2FPB2CG ┆ 135.0     ┆ 80.0      ┆ 211.0      ┆ … ┆ null      ┆ null      ┆ null        ┆ null        │
│ T16         ┆           ┆           ┆            ┆   ┆           ┆           ┆             ┆             │
│ 611A2FPB2CD ┆ 135.0     ┆ 80.0      ┆ 210.633333 ┆ … ┆ null      ┆ null      ┆ null        ┆ null        │
│ T47         ┆           ┆           ┆            ┆   ┆           ┆           ┆             ┆             │
│ 611A2APB2HP ┆ 135.0     ┆ 80.0      ┆ 210.8      ┆ … ┆ 119.98    ┆ 3649.0    ┆ 3412.0      ┆ 70.0        │
│ 205         ┆           ┆           ┆            ┆   ┆           ┆           ┆             ┆             │
│ 611A2APB2HP ┆ 135.0     ┆ 80.0      ┆ 210.766667 ┆ … ┆ 120.0     ┆ 3649.0    ┆ 4940.0      ┆ 69.0        │
│ 223         ┆           ┆           ┆            ┆   ┆           ┆           ┆             ┆             │
│ 611A2APB2HP ┆ 135.0     ┆ 80.0      ┆ 210.766667 ┆ … ┆ 120.06    ┆ 3648.0    ┆ 1938.0      ┆ 68.0        │
│ 225         ┆           ┆           ┆            ┆   ┆           ┆           ┆             ┆             │
│ 611A2FPB2C8 ┆ 135.0     ┆ 80.0      ┆ 210.666667 ┆ … ┆ null      ┆ null      ┆ null        ┆ null        │
│ T35         ┆           ┆           ┆            ┆   ┆           ┆           ┆             ┆             │
│ 611A2APB2HP ┆ 135.0     ┆ 80.0      ┆ 210.866667 ┆ … ┆ 120.0     ┆ 3648.0    ┆ 2460.0      ┆ 70.0        │
│ 201         ┆           ┆           ┆            ┆   ┆           ┆           ┆             ┆             │
│ 611A2APB2HP ┆ 135.0     ┆ 80.0      ┆ 210.733333 ┆ … ┆ 119.98    ┆ 3649.0    ┆ 1479.0      ┆ 69.0        │
│ 227         ┆           ┆           ┆            ┆   ┆           ┆           ┆             ┆             │
│ 611A2FPB2C8 ┆ 135.0     ┆ 80.0      ┆ 210.733333 ┆ … ┆ null      ┆ null      ┆ null        ┆ null        │
│ T50         ┆           ┆           ┆            ┆   ┆           ┆           ┆             ┆             │
│ 611A2APB2HP ┆ 135.0     ┆ 80.0      ┆ 210.933333 ┆ … ┆ 119.98    ┆ 3649.0    ┆ 2171.0      ┆ 70.0        │
│ 206         ┆           ┆           ┆            ┆   ┆           ┆           ┆             ┆             │
│ 611A2FPB2CB ┆ 135.0     ┆ 80.0      ┆ 210.833333 ┆ … ┆ null      ┆ null      ┆ null        ┆ null        │
│ T15         ┆           ┆           ┆            ┆   ┆           ┆           ┆             ┆             │
│ 611A2APB2HP ┆ 135.0     ┆ 80.0      ┆ 211.033333 ┆ … ┆ 120.0     ┆ 3649.0    ┆ 1885.0      ┆ 71.0        │
│ 211         ┆           ┆           ┆            ┆   ┆           ┆           ┆             ┆             │
│ 611A2FPB2CE ┆ 135.0     ┆ 80.0      ┆ 211.0      ┆ … ┆ null      ┆ null      ┆ null        ┆ null        │
│ T07         ┆           ┆           ┆            ┆   ┆           ┆           ┆             ┆             │
│ 611A2APB2HP ┆ 135.0     ┆ 80.0      ┆ 210.383333 ┆ … ┆ 120.0     ┆ 3648.0    ┆ 1465.0      ┆ 69.0        │
│ 210         ┆           ┆           ┆            ┆   ┆           ┆           ┆             ┆             │
│ 611A2APB2HP ┆ 135.0     ┆ 80.0      ┆ 210.733333 ┆ … ┆ 119.98    ┆ 3648.0    ┆ 1383.0      ┆ 68.0        │
│ 228         ┆           ┆           ┆            ┆   ┆           ┆           ┆             ┆             │
│ 611A2APB2HP ┆ 135.0     ┆ 80.0      ┆ 210.866667 ┆ … ┆ 120.0     ┆ 3648.0    ┆ 1769.0      ┆ 70.0        │
│ 214         ┆           ┆           ┆            ┆   ┆           ┆           ┆             ┆             │
└─────────────┴───────────┴───────────┴────────────┴───┴───────────┴───────────┴─────────────┴─────────────┘

In [31]:
(condition
    .join(
        eda.select([col for col in eda.columns if eda[col].null_count() == 0]),
        left_on="CF",
        right_on='ID',
        suffix="_CF",
        maintain_order="left",
    )
    .join(
        eda,
        left_on="TFT",
        right_on="ID",
        suffix=" - T",
        maintain_order="left",
    )
    .select(
        pl.col('Condition'),
        pl.col('TFT'),
        pl.col('CF'),
        pl.col('PIPR TEMP - T'),
        pl.col('PIPR TEMP').alias('PIPR TEMP - C'),
        pl.col('PIPR TIME - T'),
        pl.col('PIPR TIME').alias('PIPR TIME - C'),
        pl.col('PIPB TEMP - T'),
        pl.col('PIPB TEMP').alias('PIPB TEMP - C'),
        pl.col('PIPB TIME - T'),
        pl.col('PIPB TIME').alias('PIPB TIME - C'),
        pl.col('PAUV - T'),
        pl.col('PAUV').alias('PAUV - C'),
        pl.col('PAPB TEMP - T'),
        pl.col('PAPB TEMP').alias('PAPB TEMP - C'),
        pl.col('PAPB TIME - T'),
        pl.col('PAPB TIME').alias('PAPB TIME - C'),
        pl.col('BOOX TEMP'),
        pl.col('BOOX TIME'),
        # pl.col('ODFX Q2'),
        pl.col('SEUV') * 10, # change unit to mJ
        pl.col('SEPB TEMP'),
        pl.col('SEPB TIME'),
        pl.col("BOOX to ODF"),
        pl.col("ODF to SEUV"),
    )
    .write_excel(cwd / "eda_summary_20260302.xlsx")
)

In [35]:
qtime_raw = pl.read_excel(cwd / '6117 history-td.xlsx')

In [36]:
(
    qtime_raw
        .filter(
            pl.col("CF_GLASS_ID") != "NA",   
            pl.col("ARRAY_GLASS_ID") != "NA",   
        )
        .select("ARRAY_GLASS_ID", "CF_GLASS_ID")
        .unique()
        # .head()
        .write_excel(cwd / "tft_cf.xlsx")
)

In [37]:
(
    qtime_raw
        .filter(
            pl.col("COMPONENT_ID") == "611A2APB2HP212",
            pl.col('SUB_EQUIP_ID').str.contains(r"2CASM\d+"),
        )
        .head(20)
)

shape: (14, 42)
┌──────────────┬──────────┬─────────────┬─────────────┬───┬─────────────┬─────────────┬─────────────┬──────┐
│ STEP_ID      ┆ STEP_SEQ ┆ GLASS_ID    ┆ COMPONENT_I ┆ … ┆ CHAMBER_TIM ┆ PI_REWORK_C ┆ REWORK_COUN ┆ RN   │
│ ---          ┆ ---      ┆ ---         ┆ D           ┆   ┆ E_PATH      ┆ OUNT        ┆ T           ┆ ---  │
│ str          ┆ i64      ┆ str         ┆ ---         ┆   ┆ ---         ┆ ---         ┆ ---         ┆ i64  │
│              ┆          ┆             ┆ str         ┆   ┆ str         ┆ str         ┆ str         ┆      │
╞══════════════╪══════════╪═════════════╪═════════════╪═══╪═════════════╪═════════════╪═════════════╪══════╡
│ 6310_AS1_ARC ┆ 6310     ┆ 611A2APB2HP ┆ 611A2APB2HP ┆ … ┆             ┆             ┆             ┆ 982  │
│              ┆          ┆ 212         ┆ 212         ┆   ┆             ┆             ┆             ┆      │
│ 6310_AS1_ARC ┆ 6310     ┆ 611A2APB2HP ┆ 611A2APB2HP ┆ … ┆             ┆             ┆             ┆ 1008 │
│ _BF          ┆          ┆ 212         ┆ 212         ┆   ┆             ┆             ┆             ┆      │
│ 6310_AS1_ARO ┆ 6310     ┆ 611A2APB2HP ┆ 611A2APB2HP ┆ … ┆             ┆             ┆             ┆ 1034 │
│              ┆          ┆ 212         ┆ 212         ┆   ┆             ┆             ┆             ┆      │
│ 6310_AS1_LCD ┆ 6310     ┆ 611A2APB2HP ┆ 611A2APB2HP ┆ … ┆ 20260122151 ┆             ┆             ┆ 1060 │
│              ┆          ┆ 212         ┆ 212         ┆   ┆ 439         ┆             ┆             ┆      │
│ 6310_AS1_LCI ┆ 6310     ┆ 611A2APB2HP ┆ 611A2APB2HP ┆ … ┆ 20260122172 ┆             ┆             ┆ 1086 │
│              ┆          ┆ 212         ┆ 212         ┆   ┆ 427         ┆             ┆             ┆      │
│ 6310_AS1_LD  ┆ 6310     ┆ 611A2APB2HP ┆ 611A2APB2HP ┆ … ┆             ┆             ┆             ┆ 1112 │
│              ┆          ┆ 212         ┆ 212         ┆   ┆             ┆             ┆             ┆      │
│ 6310_AS1_ODF ┆ 6310     ┆ 611A2APB2HP ┆ 611A2APB2HP ┆ … ┆ 20260122152 ┆             ┆             ┆ 1138 │
│              ┆          ┆ 212         ┆ 212         ┆   ┆ 024         ┆             ┆             ┆      │
│ 6310_AS1_SLD ┆ 6310     ┆ 611A2APB2HP ┆ 611A2APB2HP ┆ … ┆             ┆             ┆             ┆ 1163 │
│              ┆          ┆ 212         ┆ 212         ┆   ┆             ┆             ┆             ┆      │
│ 6310_AS1_SLI ┆ 6310     ┆ 611A2APB2HP ┆ 611A2APB2HP ┆ … ┆ 20260122150 ┆             ┆             ┆ 1189 │
│ _BF          ┆          ┆ 212         ┆ 212         ┆   ┆ 955         ┆             ┆             ┆      │
│ 6310_AS1_SMO ┆ 6310     ┆ 611A2APB2HP ┆ 611A2APB2HP ┆ … ┆ 20260122162 ┆             ┆             ┆ 1215 │
│              ┆          ┆ 212         ┆ 212         ┆   ┆ 558;2026012 ┆             ┆             ┆      │
│              ┆          ┆             ┆             ┆   ┆ 2163057     ┆             ┆             ┆      │
│ 6310_AS1_TRD ┆ 6310     ┆ 611A2APB2HP ┆ 611A2APB2HP ┆ … ┆ 20260122150 ┆             ┆             ┆ 1241 │
│              ┆          ┆ 212         ┆ 212         ┆   ┆ 113         ┆             ┆             ┆      │
│ 6310_AS1_ULD ┆ 6310     ┆ 611A2APB2HP ┆ 611A2APB2HP ┆ … ┆             ┆             ┆             ┆ 1267 │
│              ┆          ┆ 212         ┆ 212         ┆   ┆             ┆             ┆             ┆      │
│ 6310_AS1_USC ┆ 6310     ┆ 611A2APB2HP ┆ 611A2APB2HP ┆ … ┆ 20260122151 ┆             ┆             ┆ 1293 │
│              ┆          ┆ 212         ┆ 212         ┆   ┆ 141         ┆             ┆             ┆      │
│ 6310_AS1_UV_ ┆ 6310     ┆ 611A2APB2HP ┆ 611A2APB2HP ┆ … ┆ 20260122152 ┆             ┆             ┆ 1319 │
│ MA           ┆          ┆ 212         ┆ 212         ┆   ┆ 252;2026012 ┆             ┆             ┆      │
│              ┆          ┆             ┆             ┆   ┆ 2152358     ┆             ┆             ┆      │
└──────────────┴──────────┴─────────────┴─────────────┴───┴─────────────┴─────────────┴─────────────┴──────┘

In [38]:
def qtime_get(
    qtime_raw: pl.DataFrame, 
    step: tuple[str, str], 
    filter: list[pl.Expr] | None = None,
) -> pl.DataFrame:
    result = (
        qtime_raw.filter(
            pl.col("STEP_ID").str.contains(step),
        )
        .select(
            pl.col("GLASS_ID").alias("ID"), 
            pl.col("TRACK_IN_TIME"),
            pl.col("TRACK_OUT_TIME"),
        )
    )
    
    if filter is not None:
        return result.filter(*filter)
    
    return result

In [39]:
t2_qtime_steps = {
    "PIPB": {"step": "6110_PI2_PIC", "filter": None},
    "PAUV": {"step": "6220_PH3_PA_UV", "filter": None},
    "PAPB": {"step": "6220_PH3_OVEN", "filter": None},
    "BOOX": {"step": "6310_AS1_ARO", "filter": None},
    "ODFX": {"step": "6310_AS1_LCD", "filter": None},
    "SEUV": {"step": "6310_AS1_UV_MA", "filter": None},
}
qtime = qtime_raw.select(pl.col("GLASS_ID").alias("ID")).unique()
for step, kwargs in t2_qtime_steps.items():
    qtime = qtime.join(
        qtime_get(qtime_raw, **kwargs)
        .select(
            "ID",
            pl.col("TRACK_IN_TIME").alias(step + "_IN"),
            pl.col("TRACK_OUT_TIME").alias(step + "_OUT"),
        ),
        on='ID',
        how='left',
    )
qtime

shape: (52, 13)
┌────────────┬────────────┬────────────┬────────────┬───┬────────────┬────────────┬────────────┬───────────┐
│ ID         ┆ PIPB_IN    ┆ PIPB_OUT   ┆ PAUV_IN    ┆ … ┆ ODFX_IN    ┆ ODFX_OUT   ┆ SEUV_IN    ┆ SEUV_OUT  │
│ ---        ┆ ---        ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---       │
│ str        ┆ datetime[m ┆ datetime[m ┆ datetime[m ┆   ┆ datetime[m ┆ datetime[m ┆ datetime[m ┆ datetime[ │
│            ┆ s]         ┆ s]         ┆ s]         ┆   ┆ s]         ┆ s]         ┆ s]         ┆ ms]       │
╞════════════╪════════════╪════════════╪════════════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ 611A2APB2H ┆ 2026-01-21 ┆ 2026-01-21 ┆ 2026-01-22 ┆ … ┆ 2026-01-23 ┆ 2026-01-23 ┆ 2026-01-23 ┆ 2026-01-2 │
│ P204       ┆ 17:13:14   ┆ 17:14:52   ┆ 13:38:05   ┆   ┆ 02:44:08   ┆ 02:47:27   ┆ 02:52:31   ┆ 3         │
│            ┆            ┆            ┆            ┆   ┆            ┆            ┆            ┆ 02:56:43  │
│ 611A2APB2H ┆ 2026-01-21 ┆ 2026-01-21 ┆ 2026-01-22 ┆ … ┆ 2026-01-22 ┆ 2026-01-22 ┆ 2026-01-22 ┆ 2026-01-2 │
│ P222       ┆ 19:44:20   ┆ 19:45:53   ┆ 00:42:50   ┆   ┆ 21:17:11   ┆ 21:20:30   ┆ 21:25:35   ┆ 2         │
│            ┆            ┆            ┆            ┆   ┆            ┆            ┆            ┆ 21:29:54  │
│ 611A2APB2H ┆ 2026-01-21 ┆ 2026-01-21 ┆ 2026-01-22 ┆ … ┆ 2026-01-22 ┆ 2026-01-22 ┆ 2026-01-22 ┆ 2026-01-2 │
│ P216       ┆ 19:41:04   ┆ 19:42:37   ┆ 00:45:32   ┆   ┆ 15:21:46   ┆ 15:25:05   ┆ 15:30:11   ┆ 2         │
│            ┆            ┆            ┆            ┆   ┆            ┆            ┆            ┆ 15:34:25  │
│ 611A2APB2H ┆ 2026-01-21 ┆ 2026-01-21 ┆ 2026-01-22 ┆ … ┆ 2026-01-22 ┆ 2026-01-22 ┆ 2026-01-22 ┆ 2026-01-2 │
│ P209       ┆ 19:50:11   ┆ 19:51:49   ┆ 00:22:39   ┆   ┆ 23:38:42   ┆ 23:41:56   ┆ 23:47:12   ┆ 2         │
│            ┆            ┆            ┆            ┆   ┆            ┆            ┆            ┆ 23:51:25  │
│ 611A2FPB2C ┆ 2026-01-21 ┆ 2026-01-21 ┆ 2026-01-22 ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ CT06       ┆ 09:50:30   ┆ 09:52:04   ┆ 17:55:22   ┆   ┆            ┆            ┆            ┆           │
│ 611A2APB2H ┆ 2026-01-21 ┆ 2026-01-21 ┆ 2026-01-22 ┆ … ┆ 2026-01-22 ┆ 2026-01-22 ┆ 2026-01-22 ┆ 2026-01-2 │
│ P228       ┆ 19:47:35   ┆ 19:49:08   ┆ 00:40:29   ┆   ┆ 22:15:09   ┆ 22:18:28   ┆ 22:23:44   ┆ 2         │
│            ┆            ┆            ┆            ┆   ┆            ┆            ┆            ┆ 22:28:05  │
│ 611A2APB2H ┆ 2026-01-21 ┆ 2026-01-21 ┆ 2026-01-22 ┆ … ┆ 2026-01-22 ┆ 2026-01-22 ┆ 2026-01-22 ┆ 2026-01-2 │
│ P207       ┆ 19:48:53   ┆ 19:50:26   ┆ 00:44:35   ┆   ┆ 15:35:59   ┆ 15:39:18   ┆ 15:44:24   ┆ 2         │
│            ┆            ┆            ┆            ┆   ┆            ┆            ┆            ┆ 15:48:37  │
│ 611A2FPB2C ┆ 2026-01-21 ┆ 2026-01-21 ┆ 2026-01-22 ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ BT54       ┆ 09:49:51   ┆ 09:51:24   ┆ 18:18:04   ┆   ┆            ┆            ┆            ┆           │
│ 611A2APB2H ┆ 2026-01-21 ┆ 2026-01-21 ┆ 2026-01-22 ┆ … ┆ 2026-01-22 ┆ 2026-01-22 ┆ 2026-01-22 ┆ 2026-01-2 │
│ P210       ┆ 19:48:14   ┆ 19:49:47   ┆ 00:23:10   ┆   ┆ 23:46:28   ┆ 23:49:52   ┆ 23:54:56   ┆ 2         │
│            ┆            ┆            ┆            ┆   ┆            ┆            ┆            ┆ 23:59:09  │
│ 611A2FPB2C ┆ 2026-01-21 ┆ 2026-01-21 ┆ 2026-01-22 ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ 8T35       ┆ 11:56:13   ┆ 11:57:36   ┆ 13:30:53   ┆   ┆            ┆            ┆            ┆           │
│ 611A2FPB2C ┆ 2026-01-21 ┆ 2026-01-21 ┆ 2026-01-22 ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ BT25       ┆ 14:38:29   ┆ 14:40:02   ┆ 00:56:45   ┆   ┆            ┆            ┆            ┆           │
│ 611A2APB2H ┆ 2026-01-21 ┆ 2026-01-21 ┆ 2026-01-22 ┆ … ┆ 2026-01-22 ┆ 2026-01-22 ┆ 2026-01-22 ┆ 2026-01-2 │
│ P227       ┆ 19:46:55   ┆ 19:48:29   ┆ 00:39:57   ┆   ┆ 22:10:52   ┆ 22:13:40   ┆ 22:18:45   ┆ 2         │
│            ┆            ┆            ┆            ┆   ┆            ┆            ┆            ┆ 22:23:07  │
│ 611A2APB2H ┆ 2026-01-21 ┆ 2026-01-21 ┆ 2026-01-22 ┆ … ┆ 2026-01-22 ┆ 2026-01-22 ┆ 2026-01-22 ┆ 2026-01-2 │
│ P215       ┆ 19:08:51   ┆ 19:10:29   ┆ 00:46:31   ┆   ┆ 16:10:51   ┆ 16:13:58   ┆ 16:19:04   ┆ 2         │
│            ┆            ┆            ┆            ┆   ┆            ┆            ┆            ┆ 16:24:50  │
│ 611A2APB2H ┆ 2026-01-21 ┆ 2026-01-21 ┆ 2026-01-22 ┆ … ┆ 2026-01-23 ┆ 2026-01-23 ┆ 2026-01-23 ┆ 2026-01-2 │
│ P203       ┆ 15:38:17   ┆ 15:39:51   ┆ 18:12:47   ┆   ┆ 04:51:36   ┆ 04:54:39   ┆ 05:00:03   ┆ 3         │
│            ┆            ┆            ┆            ┆   ┆            ┆            ┆            ┆ 05:04:19  │
│ 611A2FPB2C ┆ 2026-01-21 ┆ 2026-01-21 ┆ 2026-01-22 ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ GT16       ┆ 14:37:11   ┆ 14:38:44   ┆ 00:57:58   ┆   ┆            ┆            ┆            ┆           │
│ 611A2APB2H ┆ 2026-01-21 ┆ 2026-01-21 ┆ 2026-01-22 ┆ … ┆ 2026-01-23 ┆ 2026-01-23 ┆ 2026-01-23 ┆ 2026-01-2 │
│ P205       ┆ 15:37:38   ┆ 15:39:12   ┆ 18:13:15   ┆   ┆ 04:52:53   ┆ 04:56:55   ┆ 05:02:03   ┆ 3         │
│            ┆            ┆            ┆            ┆   ┆            ┆            ┆            ┆ 05:06:22  │
│ 611A2FPB2C ┆ 2026-01-21 ┆ 2026-01-21 ┆ 2026-01-22 ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ CT50       ┆ 14:39:48   ┆ 14:41:25   ┆ 00:31:59   ┆   ┆            ┆            ┆            ┆           │
│ 611A2FPB2C ┆ 2026-01-21 ┆ 2026-01-21 ┆ 2026-01-22 ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ DT04       ┆ 14:37:50   ┆ 14:39:24   ┆ 00:58:45   ┆   ┆            ┆            ┆            ┆           │
│ 611A2FPB2C ┆ 2026-01-21 ┆ 2026-01-21 ┆ 2026-01-22 ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ AT09       ┆ 14:33:56   ┆ 14:35:29   ┆ 01:00:53   ┆   ┆            ┆            ┆            ┆           │
│ 611A2APB2H ┆ 2026-01-21 ┆ 2026-01-21 ┆ 2026-01-22 ┆ … ┆ 2026-01-22 ┆ 2026-01-22 ┆ 2026-01-22 ┆ 2026-01-2 │
│ P218       ┆ 19:41:43   ┆ 19:43:16   ┆ 00:45:01   ┆   ┆ 15:58:30   ┆ 16:02:00   ┆ 16:07:07   ┆ 2         │
│            ┆            ┆            ┆            ┆   ┆            ┆            ┆            ┆ 16:11:20  │
│ 611A2FPB2C ┆ 2026-01-21 ┆ 2026-01-21 ┆ 2026-01-22 ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ BT16       ┆ 14:32:38   ┆ 14:34:11   ┆ 01:03:19   ┆   ┆            ┆            ┆            ┆           │
│ 611A2FPB2C ┆ 2026-01-21 ┆ 2026-01-21 ┆ 2026-01-22 ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ 8T50       ┆ 09:51:09   ┆ 09:52:47   ┆ 17:54:54   ┆   ┆            ┆            ┆            ┆           │
│ 611A2APB2H ┆ 2026-01-21 ┆ 2026-01-21 ┆ 2026-01-22 ┆ … ┆ 2026-01-23 ┆ 2026-01-23 ┆ 2026-01-23 ┆ 2026-01-2 │
│ P202       ┆ 17:12:35   ┆ 17:14:08   ┆ 17:27:34   ┆   ┆ 21:41:06   ┆ 21:45:03   ┆ 21:50:12   ┆ 3         │
│            ┆            ┆            ┆            ┆   ┆            ┆            ┆            ┆ 21:54:37  │
│ 611A2FPB2C ┆ 2026-01-21 ┆ 2026-01-21 ┆ 2026-01-22 ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ ET58       ┆ 14:33:17   ┆ 14:34:50   ┆ 01:02:19   ┆   ┆            ┆            ┆            ┆           │
│ 611A2APB2H ┆ 2026-01-21 ┆ 2026-01-21 ┆ 2026-01-22 ┆ … ┆ 2026-01-22 ┆ 2026-01-22 ┆ 2026-01-22 ┆ 2026-01-2 │
│ P219       ┆ 19:42:22   ┆ 19:43:56   ┆ 00:44:04   ┆   ┆ 15:46:14   ┆ 15:49:03   ┆ 15:54:08   ┆ 2         │
│            ┆            ┆            ┆            ┆   ┆            ┆            ┆            ┆ 15:58:22  │
│ 611A2APB2H ┆ 2026-01-21 ┆ 2026-01-21 ┆ 2026-01-22 ┆ … ┆ 2026-01-22 ┆ 2026-01-22 ┆ 2026-01-22 ┆ 2026-01-2 │
│ P220       ┆ 19:43:01   ┆ 19:44:34   ┆ 00:46:01   ┆   ┆ 16:21:33   ┆ 16:25:14   ┆ 16:30:20   ┆ 2         │
│            ┆            ┆            ┆            ┆   ┆            ┆            ┆            ┆ 16:35:55  │
│ 611A2APB2H ┆ 2026-01-21 ┆ 2026-01-21 ┆ 2026-01-22 ┆ … ┆ 2026-01-23 ┆ 2026-01-23 ┆ 2026-01-23 ┆ 2026-01-2 │
│ P214       ┆ 19:08:12   ┆ 19:09:45   ┆ 13:37:33   ┆   ┆ 02:38:32   ┆ 02:41:34   ┆ 02:46:50   ┆ 3         │
│            ┆            ┆            ┆            ┆   ┆            ┆            ┆            ┆ 02:51:03  │
│ 611A2APB2H ┆ 2026-01-21 ┆ 2026-01-21 ┆ 2026-01-22 ┆ … ┆ 2026-01-22 ┆ 2026-01-22 ┆ 2026-01-22 ┆ 2026-01-2 │
│ P221       ┆ 19:43:40   ┆ 19:45:14   ┆ 00:43:42   ┆   ┆ 17:22:17   ┆ 18:21:10   ┆ 18:28:00   ┆ 2         │
│            ┆            ┆            ┆            ┆   ┆            ┆            ┆            ┆ 18:32:13  │
│ 611A2APB2H ┆ 2026-01-21 ┆ 2026-01-21 ┆ 2026-01-22 ┆ … ┆ 2026-01-22 ┆ 2026-01-22 ┆ 2026-01-22 ┆ 2026-01-2 │
│ P213       ┆ 19:07:33   ┆ 19:09:06   ┆ 00:47:00   ┆   ┆ 11:53:51   ┆ 11:57:27   ┆ 12:02:35   ┆ 2         │
│            ┆            ┆            ┆            ┆   ┆            ┆            ┆            ┆ 12:06:49  │
│ 611A2FPB2C ┆ 2026-01-21 ┆ 2026-01-21 ┆ 2026-01-22 ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ ET14       ┆ 14:28:04   ┆ 14:29:38   ┆ 01:01:49   ┆   ┆            ┆            ┆            ┆           │
│ 611A2APB2H ┆ 2026-01-21 ┆ 2026-01-21 ┆ 2026-01-22 ┆ … ┆ 2026-01-22 ┆ 2026-01-22 ┆ 2026-01-22 ┆ 2026-01-2 │
│ P223       ┆ 19:44:59   ┆ 19:46:32   ┆ 00:42:19   ┆   ┆ 21:02:23   ┆ 21:05:35   ┆ 21:10:40   ┆ 2         │
│            ┆            ┆            ┆            ┆   ┆            ┆            ┆            ┆ 21:14:54  │
│ 611A2APB2H ┆ 2026-01-21 ┆ 2026-01-21 ┆ 2026-01-22 ┆ … ┆ 2026-01-22 ┆ 2026-01-22 ┆ 2026-01-22 ┆ 2026-01-2 │
│ P226       ┆ 19:46:16   ┆ 19:47:50   ┆ 00:41:10   ┆   ┆ 21:44:08   ┆ 21:47:23   ┆ 21:52:31   ┆ 2         │
│            ┆            ┆            ┆            ┆   ┆            ┆            ┆            ┆ 21:56:36  │
│ 611A2FPB2C ┆ 2026-01-21 ┆ 2026-01-21 ┆ 2026-01-22 ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ 9T27       ┆ 14:29:23   ┆ 14:30:56   ┆ 01:03:47   ┆   ┆            ┆            ┆            ┆           │
│ 611A2FPB2C ┆ 2026-01-21 ┆ 2026-01-21 ┆ 2026-01-22 ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ GT19       ┆ 14:27:25   ┆ 14:28:59   ┆ 11:17:53   ┆   ┆            ┆            ┆            ┆           │
│ 611A2APB2H ┆ 2026-01-21 ┆ 2026-01-21 ┆ 2026-01-22 ┆ … ┆ 2026-01-22 ┆ 2026-01-22 ┆ 2026-01-22 ┆ 2026-01-2 │
│ P225       ┆ 19:45:37   ┆ 19:47:11   ┆ 00:41:57   ┆   ┆ 21:45:25   ┆ 21:49:52   ┆ 21:56:31   ┆ 2         │
│            ┆            ┆            ┆            ┆   ┆            ┆            ┆            ┆ 22:00:40  │
│ 611A2FPB2C ┆ 2026-01-21 ┆ 2026-01-21 ┆ 2026-01-22 ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ DT35       ┆ 14:34:35   ┆ 14:36:08   ┆ 01:01:23   ┆   ┆            ┆            ┆            ┆           │
│ 611A2FPB2C ┆ 2026-01-21 ┆ 2026-01-21 ┆ 2026-01-22 ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ BT23       ┆ 14:28:43   ┆ 14:30:16   ┆ 01:00:01   ┆   ┆            ┆            ┆            ┆           │
│ 611A2FPB2C ┆ 2026-01-21 ┆ 2026-01-21 ┆ 2026-01-22 ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ BT32       ┆ 14:30:02   ┆ 14:31:35   ┆ 11:18:25   ┆   ┆            ┆            ┆            ┆           │
│ 611A2APB2H ┆ 2026-01-21 ┆ 2026-01-21 ┆ 2026-01-22 ┆ … ┆ 2026-01-23 ┆ 2026-01-23 ┆ 2026-01-23 ┆ 2026-01-2 │
│ P211       ┆ 19:06:15   ┆ 19:07:48   ┆ 11:12:50   ┆   ┆ 01:25:50   ┆ 01:30:02   ┆ 01:35:09   ┆ 3         │
│            ┆            ┆            ┆            ┆   ┆            ┆            ┆            ┆ 01:39:28  │
│ 611A2APB2H ┆ 2026-01-21 ┆ 2026-01-21 ┆ 2026-01-22 ┆ … ┆ 2026-01-23 ┆ 2026-01-23 ┆ 2026-01-23 ┆ 2026-01-2 │
│ P201       ┆ 15:38:56   ┆ 15:40:34   ┆ 17:50:26   ┆   ┆ 21:39:37   ┆ 21:42:34   ┆ 21:47:59   ┆ 3         │
│            ┆            ┆            ┆            ┆   ┆            ┆            ┆            ┆ 21:52:21  │
│ 611A2APB2H ┆ 2026-01-21 ┆ 2026-01-21 ┆ 2026-01-22 ┆ … ┆ 2026-01-22 ┆ 2026-01-22 ┆ 2026-01-22 ┆ 2026-01-2 │
│ P212       ┆ 19:06:54   ┆ 19:08:27   ┆ 00:47:31   ┆   ┆ 15:11:49   ┆ 15:15:20   ┆ 15:20:40   ┆ 2         │
│            ┆            ┆            ┆            ┆   ┆            ┆            ┆            ┆ 15:24:53  │
│ 611A2FPB2C ┆ 2026-01-21 ┆ 2026-01-21 ┆ 2026-01-22 ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ CT55       ┆ 14:39:08   ┆ 14:40:41   ┆ 00:57:16   ┆   ┆            ┆            ┆            ┆           │
│ 611A2FPB2C ┆ 2026-01-21 ┆ 2026-01-21 ┆ 2026-01-22 ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ BT15       ┆ 14:35:14   ┆ 14:36:47   ┆ 01:00:31   ┆   ┆            ┆            ┆            ┆           │
│ 611A2FPB2C ┆ 2026-01-21 ┆ 2026-01-21 ┆ 2026-01-22 ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ DT41       ┆ 12:59:39   ┆ 13:01:16   ┆ 13:30:22   ┆   ┆            ┆            ┆            ┆           │
│ 611A2FPB2C ┆ 2026-01-21 ┆ 2026-01-21 ┆ 2026-01-22 ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ DT47       ┆ 14:30:40   ┆ 14:32:14   ┆ 01:04:16   ┆   ┆            ┆            ┆            ┆           │
│ 611A2FPB2C ┆ 2026-01-21 ┆ 2026-01-21 ┆ 2026-01-22 ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ 8T42       ┆ 09:49:12   ┆ 09:50:45   ┆ 18:18:33   ┆   ┆            ┆            ┆            ┆           │
│ 611A2FPB2C ┆ 2026-01-21 ┆ 2026-01-21 ┆ 2026-01-22 ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ ET07       ┆ 14:36:32   ┆ 14:38:05   ┆ 00:59:37   ┆   ┆            ┆            ┆            ┆           │
│ 611A2FPB2C ┆ 2026-01-21 ┆ 2026-01-21 ┆ 2026-01-22 ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ BT09       ┆ 14:31:59   ┆ 14:33:32   ┆ 00:31:28   ┆   ┆            ┆            ┆            ┆           │
│ 611A2FPB2C ┆ 2026-01-21 ┆ 2026-01-21 ┆ 2026-01-22 ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ BT22       ┆ 14:35:53   ┆ 14:37:26   ┆ 00:59:07   ┆   ┆            ┆            ┆            ┆           │
│ 611A2APB2H ┆ 2026-01-21 ┆ 2026-01-21 ┆ 2026-01-22 ┆ … ┆ 2026-01-22 ┆ 2026-01-22 ┆ 2026-01-22 ┆ 2026-01-2 │
│ P208       ┆ 19:49:32   ┆ 19:51:05   ┆ 00:43:12   ┆   ┆ 17:16:16   ┆ 18:18:48   ┆ 18:23:58   ┆ 2         │
│            ┆            ┆            ┆            ┆   ┆            ┆            ┆            ┆ 18:28:11  │
│ 611A2APB2H ┆ 2026-01-21 ┆ 2026-01-21 ┆ 2026-01-22 ┆ … ┆ 2026-01-23 ┆ 2026-01-23 ┆ 2026-01-23 ┆ 2026-01-2 │
│ P206       ┆ 19:05:35   ┆ 19:07:09   ┆ 11:13:22   ┆   ┆ 01:24:31   ┆ 01:27:34   ┆ 01:32:57   ┆ 3         │
│            ┆            ┆            ┆            ┆   ┆            ┆            ┆            ┆ 01:37:14  │
│ 611A2FPB2C ┆ 2026-01-21 ┆ 2026-01-21 ┆ 2026-01-22 ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ 8T46       ┆ 14:31:20   ┆ 14:32:53   ┆ 01:02:48   ┆   ┆            ┆            ┆            ┆           │
└────────────┴────────────┴────────────┴────────────┴───┴────────────┴────────────┴────────────┴───────────┘

In [40]:
(
    condition
        .join(
            qtime.select([col for col in qtime.columns if qtime[col].null_count() == 0]),
            left_on="CF",
            right_on='ID',
            suffix="_CF",
            maintain_order="left",
        )
        .join(
            qtime,
            left_on="TFT",
            right_on="ID",
            suffix="_TFT",
            maintain_order="left",
        )
        .select(
            "Condition", "TFT", "CF",
            (pl.col('PAUV_IN'    ) - pl.col('PIPB_OUT'    )).alias('PIPB to PAPB - C'),
            (pl.col('PAUV_IN_TFT') - pl.col('PIPB_OUT_TFT')).alias('PIPB to PAPB - T'),
            (pl.col('BOOX_IN'    ) - pl.col('PAPB_OUT'    )).alias('PAPB to BOOX - C'),
            (pl.col('BOOX_IN'    ) - pl.col('PAPB_OUT_TFT')).alias('PAPB to BOOX - T'),
            # (pl.col('ODFX_IN'    ) - pl.col('LCDP_OUT'    )).alias('LCDP to ODFX'    ),
            (pl.col('SEUV_IN'    ) - pl.col('ODFX_OUT'    )).alias('ODFX to SEUV'    ),
        )
        # .write_excel(cwd / "qtime_summary.xlsx")
)

shape: (26, 8)
┌─────────────┬─────────────┬─────────────┬────────────┬────────────┬────────────┬────────────┬────────────┐
│ Condition   ┆ TFT         ┆ CF          ┆ PIPB to    ┆ PIPB to    ┆ PAPB to    ┆ PAPB to    ┆ ODFX to    │
│ ---         ┆ ---         ┆ ---         ┆ PAPB - C   ┆ PAPB - T   ┆ BOOX - C   ┆ BOOX - T   ┆ SEUV       │
│ str         ┆ str         ┆ str         ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│             ┆             ┆             ┆ duration[m ┆ duration[m ┆ duration[m ┆ duration[m ┆ duration[m │
│             ┆             ┆             ┆ s]         ┆ s]         ┆ s]         ┆ s]         ┆ s]         │
╞═════════════╪═════════════╪═════════════╪════════════╪════════════╪════════════╪════════════╪════════════╡
│ LC-1098     ┆ 611A2APB2HP ┆ 611A2FPB2CB ┆ 10h 23m    ┆ 4h 58m 28s ┆ 15h 27m    ┆ 15h 44m    ┆ 6m 50s     │
│             ┆ 221         ┆ T15         ┆ 44s        ┆            ┆ 48s        ┆ 39s        ┆            │
│ LC-1098     ┆ 611A2APB2HP ┆ 611A2FPB2CB ┆ 10h 29m    ┆ 4h 52m 7s  ┆ 15h 21m    ┆ 15h 38m 1s ┆ 5m 10s     │
│             ┆ 208         ┆ T23         ┆ 45s        ┆            ┆ 10s        ┆            ┆            │
│ STD-首件    ┆ 611A2APB2HP ┆ 611A2FPB2C9 ┆ 10h 32m    ┆ 5h 37m 54s ┆ 9h 47m 35s ┆ 10h 4m 19s ┆ 5m 8s      │
│             ┆ 213         ┆ T27         ┆ 51s        ┆            ┆            ┆            ┆            │
│ STD         ┆ 611A2APB2HP ┆ 611A2FPB2CD ┆ 10h 32m 2s ┆ 5h 39m 4s  ┆ 13h 9m 12s ┆ 13h 25m    ┆ 5m 20s     │
│             ┆ 212         ┆ T47         ┆            ┆            ┆            ┆ 56s        ┆            │
│ STD         ┆ 611A2APB2HP ┆ 611A2FPB2CE ┆ 10h 27m    ┆ 5h 2m 55s  ┆ 13h 17m    ┆ 13h 34m    ┆ 5m 6s      │
│             ┆ 216         ┆ T58         ┆ 29s        ┆            ┆ 36s        ┆ 24s        ┆            │
│ PAUV 260    ┆ 611A2APB2HP ┆ 611A2FPB2C8 ┆ 1d 1h 33m  ┆ 20h 23m    ┆ 12h 13m    ┆ 11h 58m    ┆ 5m 4s      │
│             ┆ 204         ┆ T35         ┆ 17s        ┆ 13s        ┆ 41s        ┆ 56s        ┆            │
│ PAUV 260    ┆ 611A2APB2HP ┆ 611A2FPB2CD ┆ 1d 29m 6s  ┆ 18h 27m    ┆ 12h 7m 5s  ┆ 11h 59m 7s ┆ 5m 16s     │
│             ┆ 214         ┆ T41         ┆            ┆ 48s        ┆            ┆            ┆            │
│ PAUV 220    ┆ 611A2APB2HP ┆ 611A2FPB2CG ┆ 20h 48m    ┆ 16h 6m 13s ┆ 12h 58m    ┆ 13h 4m     ┆ 5m 23s     │
│             ┆ 206         ┆ T19         ┆ 54s        ┆            ┆ 22s        ┆            ┆            │
│ PAUV 220    ┆ 611A2APB2HP ┆ 611A2FPB2CB ┆ 20h 46m    ┆ 16h 5m 2s  ┆ 13h 5m 37s ┆ 13h 11m    ┆ 5m 7s      │
│             ┆ 211         ┆ T32         ┆ 50s        ┆            ┆            ┆ 15s        ┆            │
│ 24 + 24     ┆ 611A2APB2HP ┆ 611A2FPB2C8 ┆ 1d 8h 2m   ┆ 1d 2h 9m   ┆ 1d 2h 31m  ┆ 1d 2h 35m  ┆ 5m 25s     │
│             ┆ 201         ┆ T50         ┆ 7s         ┆ 52s        ┆ 48s        ┆ 57s        ┆            │
│ 24 + 24     ┆ 611A2APB2HP ┆ 611A2FPB2CC ┆ 1d 8h 3m   ┆ 1d 13m 26s ┆ 1d 2h 38m  ┆ 1d 3h 5m   ┆ 5m 9s      │
│             ┆ 202         ┆ T06         ┆ 18s        ┆            ┆ 24s        ┆ 15s        ┆            │
│ PAPB to ARO ┆ 611A2APB2HP ┆ 611A2FPB2CB ┆ 9h 57m 56s ┆ 4h 30m 50s ┆ 22h 12m    ┆ 22h 21m 3s ┆ 5m 16s     │
│ 24 hr       ┆ 209         ┆ T09         ┆            ┆            ┆ 12s        ┆            ┆            │
│ PAPB to ARO ┆ 611A2APB2HP ┆ 611A2FPB2CC ┆ 9h 50m 34s ┆ 4h 33m 23s ┆ 22h 18m    ┆ 22h 27m    ┆ 5m 4s      │
│ 24 hr       ┆ 210         ┆ T50         ┆            ┆            ┆ 47s        ┆ 38s        ┆            │
│ PIPB to     ┆ 611A2APB2HP ┆ 611A2FPB2C8 ┆ 1d 8h 27m  ┆ 1d 2h 34m  ┆ 9h 7m 11s  ┆ 9h 12m 25s ┆ 5m 8s      │
│ PAPB 24 hr  ┆ 205         ┆ T42         ┆ 48s        ┆ 3s         ┆            ┆            ┆            │
│ PIPB to     ┆ 611A2APB2HP ┆ 611A2FPB2CB ┆ 1d 8h 26m  ┆ 1d 2h 32m  ┆ 9h 13m 46s ┆ 9h 19m     ┆ 5m 24s     │
│ PAPB 24 hr  ┆ 203         ┆ T54         ┆ 40s        ┆ 56s        ┆            ┆            ┆            │
│ ODF to SEUV ┆ 611A2APB2HP ┆ 611A2FPB2CB ┆ 10h 29m 8s ┆ 5h 36m 2s  ┆ 13h 45m    ┆ 14h 2m 14s ┆ 5m 6s      │
│ 150 s       ┆ 215         ┆ T16         ┆            ┆            ┆ 27s        ┆            ┆            │
│ ODF to SEUV ┆ 611A2APB2HP ┆ 611A2FPB2C8 ┆ 10h 29m    ┆ 5h 1m 27s  ┆ 13h 55m    ┆ 14h 12m 6s ┆ 5m 6s      │
│ 150 s       ┆ 220         ┆ T46         ┆ 55s        ┆            ┆ 19s        ┆            ┆            │
│ ODF 加抽 95 ┆ 611A2APB2HP ┆ 611A2FPB2CE ┆ 10h 32m    ┆ 5h 1m 45s  ┆ 13h 37m    ┆ 13h 54m    ┆ 5m 7s      │
│ s           ┆ 218         ┆ T14         ┆ 11s        ┆            ┆ 24s        ┆ 12s        ┆            │
│ ODF 加抽 65 ┆ 611A2APB2HP ┆ 611A2FPB2CD ┆ 10h 25m    ┆ 4h 54m 9s  ┆ 13h 25m    ┆ 13h 41m    ┆ 5m 6s      │
│ s           ┆ 207         ┆ T35         ┆ 15s        ┆            ┆ 11s        ┆ 59s        ┆            │
│ ODF 加抽 65 ┆ 611A2APB2HP ┆ 611A2FPB2CA ┆ 10h 25m    ┆ 5h 8s      ┆ 13h 31m    ┆ 13h 48m    ┆ 5m 5s      │
│ s           ┆ 219         ┆ T09         ┆ 24s        ┆            ┆ 47s        ┆ 35s        ┆            │
│ ARO to ODF  ┆ 611A2APB2HP ┆ 611A2FPB2CB ┆ 10h 21m    ┆ 4h 56m 57s ┆ 18h 20m    ┆ 18h 37m 3s ┆ 5m 5s      │
│ 60 min      ┆ 222         ┆ T22         ┆ 41s        ┆            ┆ 12s        ┆            ┆            │
│ ARO to ODF  ┆ 611A2APB2HP ┆ 611A2FPB2CE ┆ 10h 21m    ┆ 4h 55m 47s ┆ 18h 9m 38s ┆ 18h 26m    ┆ 5m 5s      │
│ 60 min      ┆ 223         ┆ T07         ┆ 32s        ┆            ┆            ┆ 29s        ┆            │
│ SEUV 5000   ┆ 611A2APB2HP ┆ 611A2FPB2CD ┆ 10h 19m    ┆ 4h 54m 46s ┆ 19h 46m    ┆ 20h 3m 8s  ┆ 6m 39s     │
│             ┆ 225         ┆ T04         ┆ 21s        ┆            ┆ 19s        ┆            ┆            │
│ SEUV 5000   ┆ 611A2APB2HP ┆ 611A2FPB2CG ┆ 10h 19m    ┆ 4h 53m 20s ┆ 19h 39m    ┆ 19h 56m    ┆ 5m 8s      │
│             ┆ 226         ┆ T16         ┆ 14s        ┆            ┆ 43s        ┆ 32s        ┆            │
│ SEUV 7000   ┆ 611A2APB2HP ┆ 611A2FPB2CB ┆ 10h 16m    ┆ 4h 51m 28s ┆ 20h 17m 7s ┆ 20h 33m    ┆ 5m 5s      │
│             ┆ 227         ┆ T25         ┆ 43s        ┆            ┆            ┆ 56s        ┆            │
│ SEUV 7000   ┆ 611A2APB2HP ┆ 611A2FPB2CC ┆ 10h 16m    ┆ 4h 51m 21s ┆ 20h 23m    ┆ 20h 40m    ┆ 5m 16s     │
│             ┆ 228         ┆ T55         ┆ 35s        ┆            ┆ 43s        ┆ 32s        ┆            │
└─────────────┴─────────────┴─────────────┴────────────┴────────────┴────────────┴────────────┴────────────┘

PI prebake 溫度, 時間  
PI postbake 溫度, 時間  
PAUV dosage  
PAPB 溫度, 時間  
ARO 溫度, 時間  
SEUV dosage  
SMO 溫度, 時間