In [1]:
from innolux import *
data_root = data_path / Path("T2_6638_ZIX-7061XX_TR35")

In [3]:
c_wip_df = pl.read_excel(data_root/"current_wip_202606171110.xlsx")

Could not determine dtype for column 19, falling back to string
Could not determine dtype for column 28, falling back to string
Could not determine dtype for column 29, falling back to string
Could not determine dtype for column 39, falling back to string
Could not determine dtype for column 49, falling back to string

In [8]:
batches = [
    "EF266143",
    "EF266144",
    "EF266146",
    "EF266147",
    "EF266148",
    "EF266149",
]

In [23]:
(c_wip_df
    .filter(pl.col("BATCH_ID").is_in(batches))
    # .filter(pl.col("BATCH_ID") == "EF266146")
    .select('BATCH_ID', "GLASS_TYPE", "GLASS_QTY", "STEP_NAME", "LAST_STEP_TRKOUT_DTTM")
    .sort(by=["BATCH_ID", "GLASS_TYPE"], descending=[False, True])
)

shape: (12, 5)
┌──────────┬────────────┬───────────┬───────────┬───────────────────────┐
│ BATCH_ID ┆ GLASS_TYPE ┆ GLASS_QTY ┆ STEP_NAME ┆ LAST_STEP_TRKOUT_DTTM │
│ ---      ┆ ---        ┆ ---       ┆ ---       ┆ ---                   │
│ str      ┆ str        ┆ i64       ┆ str       ┆ datetime[ms]          │
╞══════════╪════════════╪═══════════╪═══════════╪═══════════════════════╡
│ EF266143 ┆ TFT        ┆ 2         ┆ 6220_PHA  ┆ 2026-06-16 21:38:15   │
│ EF266143 ┆ ICF        ┆ 2         ┆ 6220_PHA  ┆ 2026-06-16 15:22:00   │
│ EF266144 ┆ TFT        ┆ 2         ┆ 6220_PHA  ┆ 2026-06-16 21:38:14   │
│ EF266144 ┆ ICF        ┆ 2         ┆ 6220_PHA  ┆ 2026-06-16 15:46:49   │
│ EF266146 ┆ TFT        ┆ 22        ┆ 6310_ASM  ┆ 2026-06-17 04:29:47   │
│ …        ┆ …          ┆ …         ┆ …         ┆ …                     │
│ EF266147 ┆ ICF        ┆ 2         ┆ 6220_PHA  ┆ 2026-06-16 15:21:56   │
│ EF266148 ┆ TFT        ┆ 2         ┆ 6220_PHA  ┆ 2026-06-16 22:45:12   │
│ EF266148 ┆ ICF        ┆ 2         ┆ 6220_PHA  ┆ 2026-06-16 15:21:54   │
│ EF266149 ┆ TFT        ┆ 2         ┆ 6220_PHA  ┆ 2026-06-16 22:45:13   │
│ EF266149 ┆ ICF        ┆ 2         ┆ 6220_PHA  ┆ 2026-06-16 15:46:54   │
└──────────┴────────────┴───────────┴───────────┴───────────────────────┘

In [18]:
tmp_df = (c_wip_df
    .filter(pl.col("BATCH_ID").is_in(batches))
    # .filter(pl.col("BATCH_ID") == "EF266143")
    .select('BATCH_ID', "GLASS_TYPE", "GLASS_QTY", "STEP_NAME", "CEL_LOTSTART_DTTM")
    .sort(by=["BATCH_ID", "GLASS_TYPE"], descending=[False, True])
)
tmp_df

shape: (12, 5)
┌──────────┬────────────┬───────────┬───────────┬─────────────────────┐
│ BATCH_ID ┆ GLASS_TYPE ┆ GLASS_QTY ┆ STEP_NAME ┆ CEL_LOTSTART_DTTM   │
│ ---      ┆ ---        ┆ ---       ┆ ---       ┆ ---                 │
│ str      ┆ str        ┆ i64       ┆ str       ┆ datetime[ms]        │
╞══════════╪════════════╪═══════════╪═══════════╪═════════════════════╡
│ EF266143 ┆ TFT        ┆ 2         ┆ 6220_PHA  ┆ 2026-06-16 17:40:15 │
│ EF266143 ┆ ICF        ┆ 2         ┆ 6220_PHA  ┆ 2026-06-16 09:48:23 │
│ EF266144 ┆ TFT        ┆ 2         ┆ 6220_PHA  ┆ 2026-06-16 17:40:15 │
│ EF266144 ┆ ICF        ┆ 2         ┆ 6220_PHA  ┆ 2026-06-16 09:48:23 │
│ EF266146 ┆ TFT        ┆ 22        ┆ 6310_ASM  ┆ 2026-06-16 17:40:15 │
│ …        ┆ …          ┆ …         ┆ …         ┆ …                   │
│ EF266147 ┆ ICF        ┆ 2         ┆ 6220_PHA  ┆ 2026-06-16 09:48:23 │
│ EF266148 ┆ TFT        ┆ 2         ┆ 6220_PHA  ┆ 2026-06-16 17:40:15 │
│ EF266148 ┆ ICF        ┆ 2         ┆ 6220_PHA  ┆ 2026-06-16 09:48:23 │
│ EF266149 ┆ TFT        ┆ 2         ┆ 6220_PHA  ┆ 2026-06-16 17:40:15 │
│ EF266149 ┆ ICF        ┆ 2         ┆ 6220_PHA  ┆ 2026-06-16 09:48:23 │
└──────────┴────────────┴───────────┴───────────┴─────────────────────┘

In [19]:
tmp_df.write_excel(data_root/"tmp.xlsx")